--- 
# -----------------------------------------------------------
# Objects computed by algorithms
# -----------------------------------------------------------

objects:
     # -----------------------------------------------------------
     # Variables
     # -----------------------------------------------------------

     # -----------------------------------------------------------
     # Waveforms
     # -----------------------------------------------------------
     RawWaveform_CH0:
       algorithm:
         name: Waveform
         format: "asdf"
       execute:
         input:
       waveform: EVENT:board_0:ch_4:waveform

     RawWaveform_CH1:
       algorithm:
         name: Waveform
         format: "asdf"
       execute:
         input:
       waveform: EVENT:board_0:ch_5:waveform


     # -----------------------------------------------------------
     # Histograms
     # -----------------------------------------------------------

     # -----------------------------------------------------------
     # Plots
     # -----------------------------------------------------------


     # -----------------------------------------------------------
     # Trees
     # -----------------------------------------------------------
     treeMaker:
         algorithm:
             name: TreeMaker
         initialise:
             output:
         execute:
             input: RawWaveform_CH0, RawWaveform_CH1
         trees:
             - Channel_0:
                 event:
                     vector:
                         double: RawWaveform_CH0
# EOF
