--- 
# -----------------------------------------------------------
# Analysis regions
# -----------------------------------------------------------
objects: 
    #muonSmallSelection:
    #    algorithm: Region
    #    input:
    #        selection: 
    #            - chargeSmallMuonCh0 >= 8800000.0
    #            - chargeSmallMuonCh1 < 8704000.0 || chargeSmallMuonCh1 >= 8705000.0
    #        weights: 
    #            - weightSmallMuonCh0
    #            - weightSmallMuonCh1
    #        is_subregion_of: 
    #            - muonSmallTrigger


    # -------------
    # Hit positions
    # -------------
    muonDetParticlePos1:
      algorithm: Region
      input:
        selection:
            - xParticleHitPos == -1000.
            - yParticleHitPos == 100.


    muonDetParticlePos2:
      algorithm: Region
      input:
        selection:
            - xParticleHitPos == -1000.
            - yParticleHitPos == 0.0

    muonDetParticlePos3:
      algorithm: Region
      input:
          selection:
            - xParticleHitPos == -1000.
            - yParticleHitPos == -100.

    muonDetParticlePos4:
      algorithm: Region
      input:
          selection:
            - xParticleHitPos == 0.0
            - yParticleHitPos == 100.

    muonDetParticlePos5:
      algorithm: Region
      input:
          selection:
            - xParticleHitPos == 0.0
            - yParticleHitPos  == 0.0
            #- "A >0  && B== False"
            #- "C< 0 || D != 1000. && F> D"
            #- "B>A   &&  A>0 || C>D || G<0 && H>0"
            #- "myWeight1, myWeighto2"
            #- "myCut1>0 && myCut2>0"
            #- "myWeight1"

    muonDetParticlePos6:
      algorithm: Region
      input:
          selection:
            - xParticleHitPos == 0.0
            - yParticleHitPos == -100.

    muonDetParticlePos7:
      algorithm: Region
      input:
          selection:
            - xParticleHitPos == 1000.
            - yParticleHitPos == 100.

    muonDetParticlePos8:
      algorithm: Region
      input:
          selection:
            - xParticleHitPos == 1000.
            - yParticleHitPos == 0.0

    muonDetParticlePos9:
      algorithm: Region
      input:
          selection:
            - xParticleHitPos == 1000.
            - yParticleHitPos == -100.

# EOF
