# -----------------------------------------------------------
# Objects computed by algorithms
# -----------------------------------------------------------

objects:
    # -----------------------------------------------------------
    # Variables
    # -----------------------------------------------------------

    simWaveforms:
        algorithm: SimulatedWaveformsBuilder
        input:
            time: Neutron_nT_timePMT_hits
            energy: Neutron_nT_photonEnPMT_hits
            hits_x_positions: Neutron_nT_xPMT_hits
            hits_y_positions: Neutron_nT_yPMT_hits
            hits_z_positions: Neutron_nT_zPMT_hits


    # Waveforms
    # -----------------------------------------------------------
    wfPMT8:
        algorithm: SimulatedWaveformsGetter
        pmt_name: PMT8
        input:
            waveform_map: simWaveforms

    wfPMT9:
        algorithm: SimulatedWaveformsGetter
        pmt_name: PMT9
        input:
            waveform_map: simWaveforms

    wfPMT12:
        algorithm: SimulatedWaveformsGetter
        pmt_name: PMT12
        input:
            waveform_map: simWaveforms

    wfPMT13:
        algorithm: SimulatedWaveformsGetter
        pmt_name: PMT13
        input:
            waveform_map: simWaveforms


    # Energies
    # -----------------------------------------------------------
    numPhotonsPMT8:
        algorithm: TimeWeightedPulse
        only_photons: True
        input:
            waveform: wfPMT8

    numPhotonsPMT9:
        algorithm: TimeWeightedPulse
        only_photons: True
        input:
            waveform: wfPMT9

    numPhotonsPMT12:
        algorithm: TimeWeightedPulse
        only_photons: True
        input:
            waveform: wfPMT12

    numPhotonsPMT13:
        algorithm: TimeWeightedPulse
        only_photons: True
        input:
            waveform: wfPMT13

    measEnergyPMT8:
        algorithm: TimeWeightedPulse
        input: 
            waveform: wfPMT8

    measEnergyPMT9:
        algorithm: TimeWeightedPulse
        input: 
            waveform: wfPMT9

    measEnergyPMT12:
        algorithm: TimeWeightedPulse
        input: 
            waveform: wfPMT12

    measEnergyPMT13:
        algorithm: TimeWeightedPulse
        input: 
            waveform: wfPMT13

    muonDetEnergy:
        algorithm: MuonDetCharge
        format: ROOT
        input:
            edep: Neutron_edepScint


    trueParticleEnergy:
        algorithm: TrueEnergy
        input:
            etrue: Neutron_ekin_particle
        
    xParticleHitPos:
        algorithm: ParticleHitPosition
        coordinate: x
        input:
            xpos: Neutron_TotT_XPosTot
            ypos: Neutron_TotT_YPosTot
            zpos: Neutron_TotT_ZPosTot

    yParticleHitPos:
        algorithm: ParticleHitPosition
        coordinate: y
        input:
            xpos: Neutron_TotT_XPosTot
            ypos: Neutron_TotT_YPosTot
            zpos: Neutron_TotT_ZPosTot

    # -----------------------------------------------------------
    # Histograms
    # -----------------------------------------------------------
    #


    # -----------------------------------------------------------
    # Plots
    # -----------------------------------------------------------
    # WARNING: there is a bug in Make1DHistPlot ovewriting instances
    # of plots in the internal dictionary. This is happening because
    # different canvases have the same name. 
    muonDetPlot1D:
        algorithm: Make1DHistPlot
        overlay: variables
        input:
            folders:
                main/pmt_variables1:
                    regions: muonDetParticlePos5, muonDetParticlePos1
                    variables:
                    - measEnergyPMT8, 30, 0., 4e-6, "# of photons", "Entries", "R:0.|G:1.0| B:0."
                    - measEnergyPMT12, 30, 0., 4e-6, "# of photons", "Entries", "R:1.0| G:1.| B:0."
                
                main/pmt_variables2:
                    regions: muonDetParticlePos5
                    variables:
                    - measEnergyPMT9, 30, 0., 4e-6, "# of photons", "Entries", "R:0.6| G:0.6| B:0.2"
                    - measEnergyPMT13, 30, 0., 4e-6, "# of photons", "Entries", "R:1.0| G:0.8| B:0.2"
                
                main:
                    regions: muonDetParticlePos5
                    variables:
                    - measEnergyPMT12, 30, 0., 4e-6, "# of photons", "Entries", "R:0.7|G:0.0|B:0.1"
                    - measEnergyPMT13, 30, 0., 4e-6, "# of photons", "Entries", "R:.2|G:.2|B:0.6"
                    
                main:
                    regions: muonDetParticlePos5
                    variables:
                    - measEnergyPMT8, 30, 0., 4e-6, "# of photons", "Entries", "R:.2|G:.6|B:.6"
                    - measEnergyPMT13, 30, 0., 4e-6, "# of photons", "Entries", "R:.1|G:1.0|B:.0"
                
                main:
                    regions: muonDetParticlePos5
                    variables:
                    - measEnergyPMT8, 30, 0., 4e-6, "# of photons", "Entries","R:0.6| G:0.6| B:0.2" 
                    - measEnergyPMT13, 30, 0., 4e-6, "# of photons", "Entries","R:0.1| G:1.0| B:0.1" 



    muonDetPlot2D:
        algorithm: Make2DHistPlot
        overlay: regions
        input:
            folders:
                main/pmt_variables1:
                    regions: muonDetParticlePos5, muonDetParticlePos1
                    variables:
                    - measEnergyPMT8, measEnergyPMT12, 30, 0., 4e-6, 30, 0., 4e-6, "Energy [MeV]", "Energy [MeV]", "R:0.|G:1.0| B:0."
                    - measEnergyPMT12, measEnergyPMT13, 30, 0., 4e-6, 30, 0., 4e-6, "Energy [MeV]", "Energy [MeV]", "R:1.0| G:1.| B:0."
                
                main/pmt_variables2:
                    regions: muonDetParticlePos5
                    variables:
                    - measEnergyPMT8, measEnergyPMT12, 30, 0., 4e-6, 30, 0., 4e-6, "Energy [MeV]", "Energy [MeV]", "R:0.6| G:0.6| B:0.2"
                    - measEnergyPMT9, measEnergyPMT13, 30, 0., 4e-6, 30, 0., 4e-6, "Energy [MeV]", "Energy [MeV]", "R:1.0| G:0.8| B:0.2"
                
                main:
                    regions: muonDetParticlePos5
                    variables:
                    - measEnergyPMT9, measEnergyPMT13, 30, 0., 4e-6, 30, 0., 4e-6, "Energy [MeV]", "Energy [MeV]", "R:0.7|G:0.0|B:0.1"
                
                main:
                    regions: muonDetParticlePos5
                    variables:
                    - measEnergyPMT8, measEnergyPMT9, 30, 0., 4e-6, 30, 0., 4e-6, "Energy [MeV]", "Energy [MeV]", "R:.2|G:.2|B:0.6"
                
                main:
                    regions: muonDetParticlePos5
                    variables:
                    - measEnergyPMT9, measEnergyPMT12, 30, 0., 4e-6, 30, 0., 4e-6, "Energy [MeV]", "Energy [MeV]", "R:.2|G:.6|B:.6" 

    muonDetPlotProfile1D:
        algorithm: Make1DProfilePlot
        overlay: regions
        input:
            folders:
                main/pmt_variables1:
                    regions: muonDetParticlePos5, muonDetParticlePos1
                    variables:
                    - measEnergyPMT8, numPhotonsPMT8, 30, 0., 4e-6, 0., 30., "Energy [MeV]", "# photons", "R:0.|G:1.0| B:0."
                    - measEnergyPMT12, numPhotonsPMT12, 30, 0., 4e-6, 0., 30., "Energy [MeV]", "# photons", "R:1.0| G:1.| B:0."
                
                main/pmt_variables2:
                    regions: muonDetParticlePos5
                    variables:
                    - measEnergyPMT8, numPhotonsPMT8, 30, 0., 4e-6, 0., 30., "Energy [MeV]", "# photons", "R:0.6| G:0.6| B:0.2"
                    - measEnergyPMT9, numPhotonsPMT9, 30, 0., 4e-6, 0., 30., "Energy [MeV]", "# photons", "R:1.0| G:0.8| B:0.2"
                
                main:
                    regions: muonDetParticlePos5
                    variables:
                    - measEnergyPMT9, numPhotonsPMT9, 30, 0., 4e-6, 0., 30., "Energy [MeV]", "# photons", "R:0.7|G:0.0|B:0.1"
                
                main:
                    regions: muonDetParticlePos5
                    variables:
                    - measEnergyPMT8, numPhotonsPMT8, 30, 0., 4e-6, 0., 30., "Energy [MeV]", "# photons", "R:.2|G:.2|B:0.6", input
                
                main:
                    regions: muonDetParticlePos5
                    variables:
                    - measEnergyPMT9, numPhotonsPMT9, 30, 0., 4e-6, 0., 30., "Energy [MeV]", "# photons", "R:.2|G:.6|B:.6" 

    # EOF
