--- 
# -----------------------------------------------------------
# Objects computed by algorithms
# -----------------------------------------------------------

objects:
     # -----------------------------------------------------------
     # Variables
     # -----------------------------------------------------------
     
     simWaveforms:
       algorithm:
         name: SimulatedWaveformsBuilder
         time: EVENT:nT:timePMT_hits
         energy: EVENT:nT:photonEnPMT_hits
         hits_x_positions: EVENT:nT:xPMT_hits
         hits_y_positions: EVENT:nT:yPMT_hits
         hits_z_positions: EVENT:nT:zPMT_hits
    

     # Waveforms
     # -----------------------------------------------------------
     wfPMT8:
       algorithm:
         name: SimulatedWaveformsGetter
         pmt_name: PMT8
       waveform_map: simWaveforms

     wfPMT9:
       algorithm:
         name: SimulatedWaveformsGetter
         pmt_name: PMT9
       waveform_map: simWaveforms

     wfPMT12:
       algorithm:
         name: SimulatedWaveformsGetter
         pmt_name: PMT12
       waveform_map: simWaveforms

     wfPMT13:
       algorithm:
         name: SimulatedWaveformsGetter
         pmt_name: PMT13
       waveform_map: simWaveforms


     # Energies
     # -----------------------------------------------------------
     numPhotonsPMT8:
         algorithm:
             name: MeasuredEnergy
             only_photons: True
         waveform: wfPMT8

     numPhotonsPMT9:
         algorithm:
             name: MeasuredEnergy
             only_photons: True
         waveform: wfPMT9

     numPhotonsPMT12:
         algorithm:
             name: MeasuredEnergy
             only_photons: True
         waveform: wfPMT12

     numPhotonsPMT13:
         algorithm:
             name: MeasuredEnergy
             only_photons: True
         waveform: wfPMT13


     measEnergyPMT8:
         algorithm:
             name: MeasuredEnergy
         waveform: wfPMT8

     measEnergyPMT9:
         algorithm:
             name: MeasuredEnergy
         waveform: wfPMT9

     measEnergyPMT12:
         algorithm:
             name: MeasuredEnergy
         waveform: wfPMT12

     measEnergyPMT13:
         algorithm:
             name: MeasuredEnergy
         waveform: wfPMT13

     muonDetEnergy:
         algorithm: 
             name: MuonDetCharge
             format: ROOT


     trueParticleEnergy:
         algorithm:
             name: TrueEnergy
         
     xParticleHitPos:
       algorithm:
         name: ParticleHitPosition
         coordinate: x

     yParticleHitPos:
       algorithm:
         name: ParticleHitPosition
         coordinate: y

     # -----------------------------------------------------------
     # Plots
     # -----------------------------------------------------------

     muonDetPlot1D:
         algorithm: 
             name: Make1DHistPlot
             folders:

               testFolder1:
                   path: pmt_variables
                   regions: muonDetParticlePos5, muonDetParticlePos1
                   variables:
                        measEnergyPMT8: 30, 0., 4e-6, "# of photons", "Entries", "R:0.|G:1.0| B:0."
                        measEnergyPMT12: 30, 0., 4e-6, "# of photons", "Entries", "R:1.0| G:1.| B:0."
                   overlay: regions

               testFolder2:
                   path: pmt_variables
                   regions: muonDetParticlePos5
                   variables:
                        measEnergyPMT9: 30, 0., 4e-6, "# of photons", "Entries", "R:0.6| G:0.6| B:0.2"
                        measEnergyPMT13: 30, 0., 4e-6, "# of photons", "Entries", "R:1.0| G:0.8| B:0.2"
                   overlay: Gamma

               testFolder3:
                   regions: muonDetParticlePos5
                   variables:
                        measEnergyPMT12: 30, 0., 4e-6, "# of photons", "Entries", "R:0.7|G:0.0|B:0.1"
                        measEnergyPMT13: 30, 0., 4e-6, "# of photons", "Entries", "R:.2|G:.2|B:0.6"
                   overlay: variables

               testFolder4:
                   regions: muonDetParticlePos5
                   variables:
                        measEnergyPMT8: 30, 0., 4e-6, "# of photons", "Entries", "R:.2|G:.6|B:.6"
                        measEnergyPMT13: 30, 0., 4e-6, "# of photons", "Entries", "R:.1|G:1.0|B:.0"
                   overlay: inputs

               testFolder5:
                   regions: muonDetParticlePos5
                   variables:
                        measEnergyPMT8: 30, 0., 4e-6, "# of photons", "Entries","R:0.6| G:0.6| B:0.2" 
                        measEnergyPMT13: 30, 0., 4e-6, "# of photons", "Entries","R:0.1| G:1.0| B:0.1" 


     muonDetPlot2D:
         algorithm: 
             name: Make2DHistPlot
             folders:

               testFolder1:
                   path: pmt_variables
                   regions: muonDetParticlePos5, muonDetParticlePos1
                   variables:
                        measEnergyPMT8, measEnergyPMT12: 30, 0., 4e-6, 30, 0., 4e-6, "Energy [MeV]", "Energy [MeV]", "R:0.|G:1.0| B:0."
                        measEnergyPMT12, measEnergyPMT13: 30, 0., 4e-6, 30, 0., 4e-6, "Energy [MeV]", "Energy [MeV]", "R:1.0| G:1.| B:0." 
                   overlay: regions
               
               testFolder2:
                   path: pmt_variables
                   regions: muonDetParticlePos5
                   variables:
                        measEnergyPMT8, measEnergyPMT12: 30, 0., 4e-6, 30, 0., 4e-6, "Energy [MeV]", "Energy [MeV]", "R:0.6| G:0.6| B:0.2" 
                        measEnergyPMT9, measEnergyPMT13: 30, 0., 4e-6, 30, 0., 4e-6, "Energy [MeV]", "Energy [MeV]", "R:1.0| G:0.8| B:0.2" 
                   overlay: Gamma
               
               testFolder3:
                   regions: muonDetParticlePos5
                   variables:
                        measEnergyPMT9, measEnergyPMT13: 30, 0., 4e-6, 30, 0., 4e-6, "Energy [MeV]", "Energy [MeV]", "R:0.7|G:0.0|B:0.1" 
                   overlay: variables
               
               testFolder4:
                   regions: muonDetParticlePos5
                   variables:
                        measEnergyPMT8, measEnergyPMT9: 30, 0., 4e-6, 30, 0., 4e-6, "Energy [MeV]", "Energy [MeV]", "R:.2|G:.2|B:0.6" 
                   overlay: inputs
               
               testFolder5:
                   regions: muonDetParticlePos5
                   variables:
                        measEnergyPMT9, measEnergyPMT12: 30, 0., 4e-6, 30, 0., 4e-6, "Energy [MeV]", "Energy [MeV]", "R:.2|G:.6|B:.6" 
     
     # -----------------------------------------------------------
     # Trees
     # -----------------------------------------------------------
     
# EOF
