--- 
# -----------------------------------------------------------
# Analysis regions
# -----------------------------------------------------------
objects: 
    muonSmallSelection:
        algorithm: Region
        check_weights_overlap: false
        selection: 
            - chargeSmallMuonCh0 >= 8800000.0
            - chargeSmallMuonCh1 < 8704000.0 || chargeSmallMuonCh1 >= 8705000.0
        weights: 
            - weightSmallMuonCh0
            - weightSmallMuonCh1
        is_subregion_of: 
            - muonSmallTrigger
  
    muonSmallTrigger: 
        algorithm: Region 
        selection: 
            - muonSmallTriggerTime < 0
    

    muonDetSel:
      algorithm: Region


    sabreTrigger: 
        algorithm: Region 
        selection: 
            - sabreTriggerTime < 0









# EOF
