--- 
# -----------------------------------------------------------
# Analysis regions
# -----------------------------------------------------------
objects: 
    muonSmallSelection:
        algorithm: 
            name: Region
            check_weights_overlap: false
        selection: 
            - chargeSmallMuonCh0 >= 8800000.0
            - chargeSmallMuonCh1 < 8704000.0 || chargeSmallMuonCh1 >= 8705000.0
        weights: 
            - weightSmallMuonCh0
            - weightSmallMuonCh1
        is_subregion_of: 
            - muonSmallTrigger
  
    muonSmallTrigger: 
        algorithm: 
            name: Region 
        selection: 
            - muonSmallTriggerTime < 0
      
    sabreTrigger: 
        algorithm: 
            name: Region 
        selection: 
            - sabreTriggerTime < 0

# EOF
