--- 
# -----------------------------------------------------------
# Analysis regions
# -----------------------------------------------------------
objects: 
    muonSelection:
        algorithm: 
            name: Region
            check_weights_overlap: false
        selection: 
            - chargeMuonCh0 >= 8800000.0
            - chargeMuonCh1 < 8704000.0 || chargeMuonCh1 >= 8705000.0
        weights: 
            - weightMuonCh0
            - weightMuonCh1
        is_subregion_of: 
            - muonTrigger
  
    muonTrigger: 
        algorithm: 
            name: Region 
        selection: 
            - muonTriggeredChannels == 16
      

# EOF
