--- 
# -----------------------------------------------------------
# Analysis regions
# -----------------------------------------------------------
objects: 
    region1:
        algorithm: 
            name: Region
            selection: var1>8, var2<var1, var3==True
            weights: weight1, weight2
  
    region1_A: 
        status: execute
        algorithm: 
            name: Region 
            selection: var4>10, var4<var1, var1>90
            weights: weight1, weight3
        contained_in: region1
      

# EOF
