--- 
# -----------------------------------------------------------
# Analysis regions
# -----------------------------------------------------------
objects: 
    muonSelection:
        algorithm: 
            name: Region
            selection: 
                - chargeMuonCh1 >= 42
                - chargeMuonCh0 >= 42
            weights: 
                - weightMuonCh0
                - weightMuonCh1
        requires: muonTrigger
  
    muonTrigger: 
        algorithm: 
            name: Region 
            selection: 
                - muonTriggeredChannels > 0
            weights: null
      

# EOF
