# -----------------------------------------------------------
# Objects computed by algorithms
# -----------------------------------------------------------

objects:
        # -----------------------------------------------------------
        # Waveform and Baseline algorithms
        # -----------------------------------------------------------

    BaselineDynamic_CH0:
        algorithm: BaselineDynamic
        samples: 40
        threshold: 20
        input:
            waveform: EVENT:board_0:ch_0:waveform


    BaselineDynamic_CH1:
        algorithm: BaselineDynamic
        samples: 40
        threshold: 20
        input:
            waveform: EVENT:board_0:ch_1:waveform

    BaselineNaive_CH0:
        algorithm: BaselineNaive
        samples: 40
        input:
            waveform: EVENT:board_0:ch_0:waveform


    BaselineNaive_CH1:
        algorithm: BaselineNaive
        samples: 40
        input:
            waveform: EVENT:board_0:ch_1:waveform


    CorrectedWaveform_CH0:
        algorithm: CorrectedWaveform
        vpp: 2.5
        adcrange: 16384
        polarity: neg
        units: mV
        input:
            waveform: EVENT:board_0:ch_0:waveform
            baseline: BaselineNaive_CH0


    CorrectedWaveform_CH1:
        algorithm: CorrectedWaveform
        vpp: 2.5
        adcrange: 16384
        polarity: neg
        units: mV
        input:
            waveform: EVENT:board_0:ch_1:waveform
            baseline: BaselineNaive_CH1

    AverageWaveform_CH0:
        algorithm: AverageWaveform
        input:
            waveform: CorrectedWaveform_CH0

    AverageWaveform_CH1:
        algorithm: AverageWaveform
        input:
            waveform: CorrectedWaveform_CH1


        # -----------------------------------------------------------
        # Window algorithms
        # -----------------------------------------------------------

    TotalWindow:
        algorithm: Window
        window: full

    PulseWindow_CH0:
        algorithm: Window
        left: -50
        right: 0
        input:
            pivot: PulseStart_CH0
    
    PulseWindow_CH1:
        algorithm: Window
        left: -50
        right: 0
        input:
            pivot: PulseStart_CH1


    PromptWindow_CH0:
        algorithm: Window
        left: -10
        right: 0
        input:
            pivot: PeakLocation_CH0
    
    PromptWindow_CH1:
        algorithm: Window
        left: -10
        right: 0
        input:
            pivot: PeakLocation_CH1


    DelayedWindow_CH0:
        algorithm: Window
        left: 0
        right: 20
        pivot index: end
        input:
            pivot: PromptWindow_CH0

    DelayedWindow_CH1:
        algorithm: Window
        left: 0
        right: 20
        pivot index: end
        input:
            pivot: PromptWindow_CH1

        # -----------------------------------------------------------
        # Variables
        # -----------------------------------------------------------

    PeakHeight_CH0:
        algorithm: PeakHeight
        window: true
        input:
            waveform: CorrectedWaveform_CH0
            window: TotalWindow

    PeakHeight_CH1:
        algorithm: PeakHeight
        window: true
        input:
            waveform: CorrectedWaveform_CH1
            window: TotalWindow

    PeakLocation_CH0:
        algorithm: PeakLocation
        window: true
        input:
            waveform: CorrectedWaveform_CH0
            window: TotalWindow
    
    PeakLocation_CH1:
        algorithm: PeakLocation
        window: true
        input:
            waveform: CorrectedWaveform_CH1
            window: TotalWindow
    
    ChargeConstant:
        algorithm: ChargeConstant
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
    
    PulseSum_CH0:
        algorithm: Sum
        input:
            waveform: CorrectedWaveform_CH0
            window: PulseWindow_CH0
    
    PulseSum_CH1:
        algorithm: Sum
        input:
            waveform: CorrectedWaveform_CH1
            window: PulseWindow_CH1

    PromptCharge_CH0:
        algorithm: Charge
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
        input:
            waveform: CorrectedWaveform_CH0
            window: PromptWindow_CH0
    
    PromptCharge_CH1:
        algorithm: Charge
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
        input:
            waveform: CorrectedWaveform_CH1
            window: PromptWindow_CH1

    DelayedCharge_CH0:
        algorithm: Charge
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
        input:
            waveform: CorrectedWaveform_CH0
            window: DelayedWindow_CH0
    
    DelayedCharge_CH1:
        algorithm: Charge
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
        input:
            waveform: CorrectedWaveform_CH1
            window: DelayedWindow_CH1

    TotalCharge_CH0:
        algorithm: Charge
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
        input:
            waveform: CorrectedWaveform_CH0
            window: TotalWindow
    
    TotalCharge_CH1:
        algorithm: Charge
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
        input:
            waveform: CorrectedWaveform_CH1
            window: TotalWindow

    PulseCharge_CH0:
        algorithm: Charge
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
        input:
            waveform: CorrectedWaveform_CH0
            window: PulseWindow_CH0
    
    PulseCharge_CH1:
        algorithm: Charge
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
        input:
            waveform: CorrectedWaveform_CH1
            window: PulseWindow_CH1


    PulseStart_CH0:
        algorithm:  CFD
        delay: 5
        scale: 1
        cfd_threshold: 15
        input:
            waveform: CorrectedWaveform_CH0
        output:
            times: PulseCFDTimes_CH0
            trace: PulseCFDTrace_CH0


    PulseStart_CH1:
        algorithm: CFD
        delay: 5
        scale: 1
        cfd_threshold: 15
        input:
            waveform: CorrectedWaveform_CH1
        output:
            times: PulseCFDTimes_CH1
            trace: PulseCFDTrace_CH1

    TrapezoidWaveform_CH0:
        algorithm: TrapezoidFilter
        rise: 10
        gap: 10
        rate: 500e6
        tau: 2e-6
        zeropole: true
        input:
            waveform: CorrectedWaveform_CH0

    TrapezoidWaveform_CH1:
        algorithm: TrapezoidFilter
        rise: 10
        gap: 10
        rate: 500e6
        tau: 2e-6
        zeropole: true
        input:
            waveform: CorrectedWaveform_CH1

    CFD_CH0:
        algorithm: CFD
        delay: 5
        scale: 1
        cfd_threshold: 10
        savecfd: True
        input:
            waveform: TrapezoidWaveform_CH0
        output:
            times: CFD_CH0:CFDTimes_CH0
            trace: CFD_CH0:CFDTrace_CH0
    
    CFD_CH1:
        algorithm: CFD
        delay: 5
        scale: 1
        cfd_threshold: 10
        savecfd: True
        input:
            waveform: TrapezoidWaveform_CH1
        output:
            times: CFD_CH1:CFDTimes_CH1
            trace: CFD_CH1:CFDTrace_CH1

    PromptDelayChargeRatio_CH0:
        algorithm: Ratio
        input:
            numerator: PromptCharge_CH0
            denominator: DelayedCharge_CH0

    PromptDelayChargeRatio_CH1:
        algorithm: Ratio
        input:
            numerator: PromptCharge_CH1
            denominator: DelayedCharge_CH1

    MeanTime_CH0:
        algorithm: MeanTime
        rate: 500e6
        input:
            waveform: CorrectedWaveform_CH0
            window: PulseWindow_CH0
    
    MeanTime_CH1:
        algorithm: MeanTime
        rate: 500e6
        input:
            waveform: CorrectedWaveform_CH1
            window: PulseWindow_CH1


######### !! Will need a custom config #########
    PromptDelayChargeRatioCalculator_CH0:
        algorithm: Calculator
        equation: A+(A+B)*(C+D)
        input:
            variables:
                A: 1
                B: 11.5
                C: PromptCharge_CH0
                D: 3e-1
    
    PromptDelayChargeRatioCalculator_CH1:
        algorithm: Calculator
        equation: A+(A+B)*(C+D)
        input:
            variables:
                A: 1
                B: 11.5
                C: PromptCharge_CH1
                D: 3e-1

    PulseTime_CH0:
        algorithm: TimeConverter
        rate: 500e6
        unit: ns
        input:
            sample_number: PulseStart_CH0


    PulseTime_CH1:
        algorithm: TimeConverter
        rate: 500e6
        unit: ns
        input:
            sample_number: PulseStart_CH1

    TimeDifference_CH01:
        algorithm: Difference
        input:
            x1: PulseTime_CH0
            x2: PulseTime_CH1

    Moments_CH0:
        algorithm: Moment
        rate: 500e6
        input:
            waveform: CorrectedWaveform_CH0
            window: TotalWindow
        output:
            mean: Moments_CH0:Mean_CH0
            stddev: Moments_CH0:Stddev_CH0
            skew: Moments_CH0:Skew_CH0
            kurtosis: Moments_CH0:Kurtosis_CH0
    
    Moments_CH1:
        algorithm: Moment
        rate: 500e6
        input:
            waveform: CorrectedWaveform_CH1
            window: TotalWindow
        output:
            mean: Moments_CH1:Mean_CH1
            stddev: Moments_CH1:Stddev_CH1
            skew: Moments_CH1:Skew_CH1
            kurtosis: Moments_CH1:Kurtosis_CH1


    DAMAX1_CH0:
        algorithm: DAMAX1
        rate: 500e6
        cfd_delay: 10
        input:
            waveform: CorrectedWaveform_CH0
            pulse_start: PulseStart_CH0
    
    DAMAX1_CH1:
        algorithm: DAMAX1
        rate: 500e6
        cfd_delay: 10
        input:
            waveform: CorrectedWaveform_CH1
            pulse_start: PulseStart_CH1

    DAMAX2_CH0:
        algorithm: DAMAX2
        rate: 500e6
        cfd_delay: 10
        input:
            waveform: CorrectedWaveform_CH0
            pulse_start: PulseStart_CH0
    
    DAMAX2_CH1:
        algorithm: DAMAX2
        rate: 500e6
        cfd_delay: 10
        input:
            waveform: CorrectedWaveform_CH1
            pulse_start: PulseStart_CH1
        
    FFT_CH0:
        algorithm: FFT
        rate: 500e6
        bins: 100
        input:
            waveform: CorrectedWaveform_CH0
            window: PulseWindow_CH0
    
    FFT_CH1:
        algorithm: FFT
        rate: 500e6
        bins: 100
        input:
            waveform: CorrectedWaveform_CH1
            window: PulseWindow_CH1

    LeadingEdge_CH0:
        algorithm: LeadingEdgeThreshold
        offset: 5
        threshold: 5
        input:
            waveform: CorrectedWaveform_CH0
    
    LeadingEdge_CH1:
        algorithm: LeadingEdgeThreshold
        offset: 5
        threshold: 5
        input:
            waveform: CorrectedWaveform_CH1


        # -----------------------------------------------------------
        # Trees
        # -----------------------------------------------------------
        #
    TreeMaker:
        algorithm: TreeMaker
        input:
            trees:
            - Channel_0:
                    event:
                        vector<int>: {RawWaveform: EVENT:board_0:ch_0:waveform}
                        vector<float>: {CorrectedWaveform: CorrectedWaveform_CH0}
                        vector<double>:
                                    - FFT_CH0, Moments_CH0
                                    - {CFDTrace: CFD_CH0:CFDTrace_CH0,
                                       CFDTimes: CFD_CH0:CFDTimes_CH0}
                        float:
                            -   BaselineDynamic_CH0, BaselineNaive_CH0,
                                PromptDelayChargeRatioCalculator_CH0, CFD_CH0,
                                PulseCharge_CH0, TotalCharge_CH0
                            -   {DAMAX1: DAMAX1_CH0, DAMAX2: DAMAX2_CH0}
                            -   LeadingEdge_CH0, MeanTime_CH0
                            -   {Mean: Moments_CH0:Mean_CH0,
                                 Stddev: Moments_CH0:Stddev_CH0,
                                 Skew: Moments_CH0:Skew_CH0,
                                 Kurtosis: Moments_CH0:Kurtosis_CH0}
                            -   PeakHeight_CH0, PeakLocation_CH0, PulseStart_CH0,
                                PulseTime_CH0, PromptDelayChargeRatio_CH0,
                                PulseSum_CH0

            - Single_channel_0:
                single:
                    vector<double>: AverageWaveform_CH0
                    double: ChargeConstant

            # - Channel_1:
            #         single:
            #             vector<double>: AverageWaveform_CH1
            #             double: ChargeConstant
            #         event:
            #             vector<int>: {RawWaveform: EVENT:board_0:ch_1:waveform}
            #             vector<float>: {CorrectedWaveform: CorrectedWaveform_CH1}
            #             vector<double>:
            #                         - FFT_CH1, Moments_CH1
            #                         - {CFDTrace: CFD_CH1:CFDTrace_CH1,
            #                            CFDTimes: CFD_CH1:CFDTimes_CH1}
            #             float:
            #                 -   BaselineDynamic_CH1, BaselineNaive_CH1,
            #                     PromptDelayChargeRatioCalculator_CH1, CFD_CH1,
            #                     PulseCharge_CH1, TotalCharge_CH1
            #                 -   {DAMAX1: DAMAX1_CH1, DAMAX2: DAMAX2_CH1}
            #                 -   LeadingEdge_CH1, MeanTime_CH1
            #                 -   {Mean: Moments_CH1:Mean_CH1,
            #                      Stddev: Moments_CH1:Stddev_CH1,
            #                      Skew: Moments_CH1:Skew_CH1,
            #                      Kurtosis: Moments_CH1:Kurtosis_CH1}
            #                 -   PeakHeight_CH1, PeakLocation_CH1, PulseStart_CH1,
            #                     PulseTime_CH1, PromptDelayChargeRatio_CH1,
            #                     PulseSum_CH1
            #                 -   Timestamp: Timestamp_CH1

            # - MultiChannel:
            #         event:
            #             float: TimeDifference_CH01
