# -----------------------------------------------------------
# Objects computed by algorithms
# -----------------------------------------------------------

objects:
    # -----------------------------------------------------------
    # Variables
    # -----------------------------------------------------------

    ############################## WAVEFORMS AND BASELINE #################################

    RawWaveform_CHX:
        algorithm: 
            name: RawWaveform
        initialise:
            output:
        execute:
            input: EVENT:board_0:ch_x:waveform,
                   EVENT:board_0:raw_waveform_ch_x,
                   EVENT:RawWaveform
            output:
        waveform_bt: EVENT:board_0:raw_waveform_ch_x # Channels need to be specified here
        waveform_md: EVENT:board_0:ch_x:waveform
        waveform_wd: EVENT:RawWaveform

    BaselineDynamic_CHX:
        algorithm: 
            name: BaselineDynamic
            samples: 40
            threshold: 20
        execute:
            input: RawWaveform_CHX
        waveform: RawWaveform_CHX

    BaselineNaive_CHX:
        algorithm: 
            name: BaselineNaive
            samples: 40
        execute:
            input: RawWaveform_CHX
        waveform: RawWaveform_CHX

    CorrectedWaveform_CHX:
        algorithm: 
            name: CorrectedWaveform
            vpp: 2.5
            adcrange: 16384
            polarity: neg
            units: mV
        initialise:
            output:
        execute:
            input: RawWaveform_CHX, BaselineNaive_CHX
        waveform: RawWaveform_CHX
        baseline: BaselineNaive_CHX
        wc_waveform: EVENT:GROUP:CHX:RawWaveform

    AverageWaveform_CHX:
        algorithm:
            name: AverageWaveform
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CHX
        finalise:
            output:
        waveform: CorrectedWaveform_CHX

    ############################## WINDOWS #################################

    TotalWindow_CHX:
        algorithm:
            name: Window
            window: full
        initialise:
            output:
        execute:
            output:

    PulseWindow_CHX:
        algorithm:
            name: Window
            left: 0
            right: 50
        initialise:
            output:
        execute:
            input: PulseStart_CHX
        pivot: PulseStart_CHX

    PromptWindow_CHX:
        algorithm:
            name: Window
            left: 2
            right: 10
        initialise:
            output:
        execute:
            input: PeakLocation_CHX
        pivot: PeakLocation_CHX

    DelayedWindow_CHX:
        algorithm:
            name: Window
            left: 0
            right: 20
            pivot index: end
        initialise:
            output:
        execute:
            input: PromptWindow_CHX
        pivot: PromptWindow_CHX

    ############################## VARIABLES #################################

    Timestamp_CHX:
        algorithm:
            name: GetTimestamp
        execute:
            output:

    PeakHeight_CHX:
        algorithm:
            name: PeakHeight
            window: True
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CHX, TotalWindow_CHX
        waveform: CorrectedWaveform_CHX
        window: TotalWindow_CHX

    PeakLocation_CHX:
        algorithm:
            name: PeakLocation
            window: True
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CHX, TotalWindow_CHX
        waveform: CorrectedWaveform_CHX
        window: TotalWindow_CHX

    PromptCharge_CHX:
        algorithm:
            name: Charge
            impedance: 50
            rate: 500e6
            unit: pC
            waveform_unit: mV
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CHX, PromptWindow_CHX
        waveform: CorrectedWaveform_CHX
        window: PromptWindow_CHX

    DelayedCharge_CHX:
        algorithm:
            name: Charge
            impedance: 50
            rate: 500e6
            unit: pC
            waveform_unit: mV
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CHX, DelayedWindow_CHX
        waveform: CorrectedWaveform_CHX
        window: DelayedWindow_CHX

    TotalCharge_CHX:
        algorithm:
            name: Charge
            impedance: 50
            rate: 500e6
            unit: pC
            waveform_unit: mV
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CHX, TotalWindow_CHX
        waveform: CorrectedWaveform_CHX
        window: TotalWindow_CHX

    PulseCharge_CHX:
        algorithm:
            name: Charge
            impedance: 50
            rate: 500e6
            unit: pC
            waveform_unit: mV
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CHX, PulseWindow_CHX
        waveform: CorrectedWaveform_CHX
        window: PulseWindow_CHX

    PulseStart_CHX:
        algorithm:
            name: CFD
            delay: 5
            scale: 1
            cfd_threshold: 1
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CHX
        waveform: CorrectedWaveform_CHX

    PromptDelayChargeRatio_CHX:
        algorithm:
            name: Ratio
        execute:
            input: PromptCharge_CHX, DelayCharge_CHX
        x1: PromptCharge_CHX
        x2: DelayedCharge_CHX

    MeanTime_CHX:
        algorithm:
            name: MeanTime
            rate: 500e6
        initialise:
            input:
        execute:
            input: CorrectedWaveform_CHX, PulseWindow_CHX
        waveform: CorrectedWaveform_CHX
        window: PulseWindow_CHX

    PromptDelayChargeRatioCalculator_CHX:
        algorithm:
            name: Calculator
        equation: A+(A+B)*(C+D)
        variables:
          A: 1
          B: 11.5
          C: PromptCharge_CHX
          D: 3e-1
        initialise:
            input:
        execute:
            input: PromptCharge_CHX

    PulseTime_CHX:
        algorithm:
            name: TimeConverter
            rate: 500e6
            unit: ns
        initialise:
            output:
        execute:
            input: PulseStart_CHX
        time: PulseStart_CHX

    TimeDifference_CH01:
        algorithm:
            name: Difference
        execute:
            input: PulseTime_CH0, PulseTime_CH1
        x1: PulseTime_CH0
        x2: PulseTime_CH1

    Moments_CHX:
        algorithm:
            name: Moment
            rate: 500e6
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CHX, TotalWindow_CHX
        waveform: CorrectedWaveform_CHX
        window: TotalWindow_CHX
    
    DAMAX1_CHX:
        algorithm:
            name: DAMAX1
            rate: 500e6
            cfd_delay: 10
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CHX, PulseStart_CHX
        waveform: CorrectedWaveform_CHX
        pulse_start: PulseStart_CHX

    DAMAX2_CHX:
        algorithm:
            name: DAMAX2
            rate: 500e6
            cfd_delay: 10
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CHX, PulseStart_CHX
        waveform: CorrectedWaveform_CHX
        pulse_start: PulseStart_CHX

    FFT_CHX:
        algorithm:
            name: FFT
            rate: 500e6
            bins: 100
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CHX, PulseWindow_CHX
        waveform: CorrectedWaveform_CHX
        #window: PulseWindow_CHX

    LeadingEdge_CHX:
        algorithm:
            name: LeadingEdgeThreshold
            offset: 5
            threshold: 5
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CHX
        waveform: CorrectedWaveform_CHX

    # -----------------------------------------------------------
    # Trees
    # -----------------------------------------------------------

    TreeMaker:
        algorithm:
            name: TreeMaker
        initialise:
            output:
        execute:
            input: RawWaveform_CHX, CorrectedWaveform_CHX, BaselineDynamic_CHX, BaselineNaive_CHX, PeakHeight_CHX,
                   PeakLocation_CHX, PulseCharge_CHX, TotalCharge_CHX, PulseStart_CHX, 
                   PulseTime_CHX, PromptDelayChargeRatio_CHX, PromptCharge_CHX, DelayedCharge_CHX, 
                   MeanTime_CHX, PromptDelayChargeRatioCalculator_CHX, TimeDifference_CH01, Moments_CHX, 
                   Timestamp_CHX, AverageWaveform_CHX, DAMAX1_CHX, DAMAX2_CHX, FFT_CHX, LeadingEdge_CHX
        finalise:
            output:
        trees:
            - Channel_X:
                channels: global
                event:
                    vector<int>: RawWaveform_CHX
                    vector<double>: CorrectedWaveform_CHX, FFT_CHX, Moments_CHX
                    float:  BaselineDynamic_CHX, BaselineNaive_CHX, PeakHeight_CHX, PeakLocation_CHX, PulseCharge_CHX, 
                            TotalCharge_CHX, PulseStart_CHX, PulseTime_CHX, PromptDelayChargeRatio_CHX, 
                            MeanTime_CHX, PromptDelayChargeRatioCalculator_CHX,
                            Timestamp_CHX, DAMAX1_CHX, DAMAX2_CHX, LeadingEdge_CHX
                single:
                    vector<double>: AverageWaveform_CHX
        
            - Channel_01:
                event:
                    float: TimeDifference_CH01
