# -----------------------------------------------------------
# Objects computed by algorithms
# -----------------------------------------------------------

objects:
        # -----------------------------------------------------------
        # Waveform and Baseline algorithms
        # -----------------------------------------------------------

    RawWaveform_CH0:
        algorithm:
            name: RawWaveform
        initialise:
            output:
        execute:
            input: EVENT:board_0:ch_0:waveform, EVENT:board_0:raw_waveform_ch_0, EVENT:RawWaveform
            output:
        waveform_bt: EVENT:board_0:raw_waveform_ch_0         # Channels need to be specified here
        waveform_md: EVENT:board_0:ch_0:waveform
        waveform_wd: EVENT:RawWaveform


    RawWaveform_CH1:
        algorithm:
            name: RawWaveform
        initialise:
            output:
        execute:
            input: EVENT:board_0:ch_1:waveform, EVENT:board_0:raw_waveform_ch_1, EVENT:RawWaveform
            output:
        waveform_bt: EVENT:board_0:raw_waveform_ch_1         # Channels need to be specified here
        waveform_md: EVENT:board_0:ch_1:waveform
        waveform_wd: EVENT:RawWaveform


    BaselineDynamic_CH0:
        algorithm:
            name: BaselineDynamic
            samples: 40
            threshold: 20
        execute:
            input: RawWaveform_CH0
        waveform: RawWaveform_CH0


    BaselineDynamic_CH1:
        algorithm:
            name: BaselineDynamic
            samples: 40
            threshold: 20
        execute:
            input: RawWaveform_CH1
        waveform: RawWaveform_CH1

    BaselineNaive_CH0:
        algorithm:
            name: BaselineNaive
            samples: 40
        execute:
            input: RawWaveform_CH0
        waveform: RawWaveform_CH0


    BaselineNaive_CH1:
        algorithm:
            name: BaselineNaive
            samples: 40
        execute:
            input: RawWaveform_CH1
        waveform: RawWaveform_CH1


    CorrectedWaveform_CH0:
        algorithm:
            name: CorrectedWaveform
            vpp: 2.5
            adcrange: 16384
            polarity: neg
            units: mV
        initialise:
            output:
        execute:
            input: RawWaveform_CH0, BaselineNaive_CH0
        waveform: RawWaveform_CH0
        baseline: BaselineNaive_CH0
        wc_waveform: EVENT:GROUP:CH0:RawWaveform


    CorrectedWaveform_CH1:
        algorithm:
            name: CorrectedWaveform
            vpp: 2.5
            adcrange: 16384
            polarity: neg
            units: mV
        initialise:
            output:
        execute:
            input: RawWaveform_CH1, BaselineNaive_CH1
        waveform: RawWaveform_CH1
        baseline: BaselineNaive_CH1
        wc_waveform: EVENT:GROUP:CH1:RawWaveform

    AverageWaveform_CH0:
        algorithm:
            name: AverageWaveform
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CH0
        finalise:
            output:
        waveform: CorrectedWaveform_CH0

    AverageWaveform_CH1:
        algorithm:
            name: AverageWaveform
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CH1
        finalise:
            output:
        waveform: CorrectedWaveform_CH1


        # -----------------------------------------------------------
        # Window algorithms
        # -----------------------------------------------------------

    TotalWindow:
        algorithm:
            name: Window
            window: full
        initialise:
            output:
        execute:
            output:


    PulseWindow_CH0:
        algorithm:
            name: Window
            left: -50
            right: 0
        initialise:
            output:
        execute:
            input: PulseStart_CH0
        pivot: PulseStart_CH0


    PromptWindow_CH0:
        algorithm:
            name: Window
            left: -10
            right: 0
        initialise:
            output:
        execute:
            input: PeakLocation_CH0
        pivot: PeakLocation_CH0


    DelayedWindow_CH0:
        algorithm:
            name: Window
            left: 0
            right: 20
            pivot index: end
        initialise:
            output:
        execute:
            input: PromptWindow_CH0
        pivot: PromptWindow_CH0


        # -----------------------------------------------------------
        # Variables
        # -----------------------------------------------------------

    Timestamp_CH0:
        algorithm:
            name: GetTimestamp
        execute:
            output:

    PeakHeight_CH0:
        algorithm:
            name: PeakHeight
            window: true
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CH0, TotalWindow
        waveform: CorrectedWaveform_CH0
        window: TotalWindow


    PeakLocation_CH0:
        algorithm:
            name: PeakLocation
            window: true
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CH0, TotalWindow
        waveform: CorrectedWaveform_CH0
        window: TotalWindow


    PromptCharge_CH0:
        algorithm:
            name: Charge
            impedance: 50
            rate: 500e6
            unit: pC
            waveform_unit: mV
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CH0, PromptWindow_CH0
        waveform: CorrectedWaveform_CH0
        window: PromptWindow_CH0


    DelayedCharge_CH0:
        algorithm:
            name: Charge
            impedance: 50
            rate: 500e6
            unit: pC
            waveform_unit: mV
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CH0, DelayedWindow_CH0
        waveform: CorrectedWaveform_CH0
        window: DelayedWindow_CH0


    TotalCharge_CH0:
        algorithm:
            name: Charge
            impedance: 50
            rate: 500e6
            unit: pC
            waveform_unit: mV
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CH0, TotalWindow
        waveform: CorrectedWaveform_CH0
        window: TotalWindow


    PulseCharge_CH0:
        algorithm:
            name: Charge
            impedance: 50
            rate: 500e6
            unit: pC
            waveform_unit: mV
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CH0, PulseWindow_CH0
        waveform: CorrectedWaveform_CH0
        window: PulseWindow_CH0


    PulseStart_CH0:
        algorithm:
            name: CFD
            delay: 5
            scale: 1
            cfd_threshold: 1
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CH0
        waveform: CorrectedWaveform_CH0


    PulseStart_CH1:
        algorithm:
            name: CFD
            delay: 5
            scale: 1
            cfd_threshold: 1
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CH1
        waveform: CorrectedWaveform_CH1


        # CFD_CHX:
        #         algorithm:
        #                 name: CFD
        #                 delay: 5
        #                 scale: 1
        #                 cfd_threshold: 10
        #                 savecfd: True
        #         initialise:
        #                 output:
        #         execute:
        #                 input: TrapezoidWaveform
        #         waveform: TrapezoidWaveform


    PromptDelayChargeRatio_CH0:
        algorithm:
            name: Ratio
        execute:
            input: PromptCharge_CH0, DelayedCharge_CH0
        x1: PromptCharge_CH0
        x2: DelayedCharge_CH0


    MeanTime_CH0:
        algorithm:
            name: MeanTime
            rate: 500e6
        initialise:
            input:
        execute:
            input: CorrectedWaveform_CH0, PulseWindow_CH0
        waveform: CorrectedWaveform_CH0
        window: PulseWindow_CH0


    PromptDelayChargeRatioCalculator_CH0:
        algorithm:
            name: Calculator
        equation: A+(A+B)*(C+D)
        variables:
            A: 1
            B: 11.5
            C: PromptCharge_CH0
            D: 3e-1
        initialise:
            input:
        execute:
            input: PromptCharge_CH0


    PulseTime_CH0:
        algorithm:
            name: TimeConverter
            rate: 500e6
            unit: ns
        initialise:
            output:
        execute:
            input: PulseStart_CH0
        time: PulseStart_CH0


    PulseTime_CH1:
        algorithm:
            name: TimeConverter
            rate: 500e6
            unit: ns
        initialise:
            output:
        execute:
            input: PulseStart_CH1
        time: PulseStart_CH1


    TimeDifference_CH01:
        algorithm:
            name: Difference
        execute:
            input: PulseTime_CH0, PulseTime_CH1
        x1: PulseTime_CH0
        x2: PulseTime_CH1

    Moments_CH0:
        algorithm:
            name: Moment
            rate: 500e6
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CH0, TotalWindow
        waveform: CorrectedWaveform_CH0
        window: TotalWindow


    DAMAX1_CH0:
        algorithm:
            name: DAMAX1
            rate: 500e6
            cfd_delay: 10
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CH0, PulseStart_CH0
        waveform: CorrectedWaveform_CH0
        pulse_start: PulseStart_CH0

    DAMAX2_CH0:
        algorithm:
            name: DAMAX2
            rate: 500e6
            cfd_delay: 10
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CH0, PulseStart_CH0
        waveform: CorrectedWaveform_CH0
        pulse_start: PulseStart_CH0
        
    FFT_CH0:
        algorithm:
            name: FFT
            rate: 500e6
            bins: 100
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CH0, PulseWindow_CH0
        waveform: CorrectedWaveform_CH0
        window: PulseWindow_CH0

    LeadingEdge_CH0:
        algorithm:
            name: LeadingEdgeThreshold
            offset: 5
            threshold: 5
        initialise:
            output:
        execute:
            input: CorrectedWaveform_CH0
        waveform: CorrectedWaveform_CH0

    # Only relevant for PSD reader
    SubEventTimestamp_CH0:
        algorithm:
            name: ChannelTimestamps
            channel: 0
        execute:
            output:


        # -----------------------------------------------------------
        # Trees
        # -----------------------------------------------------------
        #
    TreeMaker:
        algorithm:
            name: TreeMaker
        initialise:
            output:
        execute:
            input: RawWaveform_CH0, CorrectedWaveform_CH0, BaselineDynamic_CH0, BaselineNaive_CH0, PeakHeight_CH0,
                PeakLocation_CH0, PulseCharge_CH0, TotalCharge_CH0, PulseStart_CH0, PulseStart_CH1,
                PulseTime_CH0, PulseTime_CH1, PromptDelayChargeRatio_CH0, PromptCharge_CH0,
                DelayedCharge_CH0, MeanTime_CH0, PromptDelayChargeRatioCalculator_CH0, TimeDifference_CH01,
                Moments_CH0, Timestamp_CH0, AverageWaveform_CH0, AverageWaveform_CH1, DAMAX1_CH0, DAMAX2_CH0, FFT_CH0, LeadingEdge_CH0,
                SubEventTimestamp_CH0
        finalise:
            output:

        trees:
        - Channel_0:
                event:
                    vector<int>: RawWaveform_CH0
                    vector<double>: 
                                - FFT_CH0, Moments_CH0
                                - CorrectedWaveform: CorrectedWaveform_CH0
                    float: 
                        -   PeakHeight_CH0, PeakLocation_CH0, PulseCharge_CH0,
                            TotalCharge_CH0, PulseStart_CH0, PulseTime_CH0, PromptDelayChargeRatio_CH0,
                            MeanTime_CH0, PromptDelayChargeRatioCalculator_CH0,
                            LeadingEdge_CH0, BaselineDynamic_CH0, BaselineNaive_CH0, SubEventTimestamp_CH0
                        - Timestamp: Timestamp_CH0
                        - {DAMAX1: DAMAX1_CH0, DAMAX2_CH0: DAMAX2_CH0}
                single:
                    vector<double>: AverageWaveform_CH0

        - Channel_1:
                event:
                    float: PulseStart_CH1, PulseTime_CH1
                single:
                    vector<double>: AverageWaveform_CH1

        - MultiChannel:
                event:
                    float: TimeDifference_CH01
