<channels>: [0, 1]
# -----------------------------------------------------------
# Objects computed by algorithms
# -----------------------------------------------------------

objects:
        # -----------------------------------------------------------
        # Waveform and Baseline algorithms
        # -----------------------------------------------------------
    SwinburneSC:
        algorithm: SwinburneSC
        dir: /home/msmg/data/spartan/ostanley/slow_control/
        epochtime: 1644991273
        input:
          timestamp: EVENT:board_0:ch_0:ch_timestamp
        output:
          temp: cRIO_RTD_1

    TEMP1:
        algorithm: EPICSArchiveIP
        ip: 10.100.13.78:17668
        epochtime: 1644991273
        pv: HILDAQ:elapsedTime
        input:
          timestamp: EVENT:board_0:ch_0:ch_timestamp

    TEMP2:
        algorithm: EPICSArchivePB
        dir: /home/msmg/data/arch
        epochtime: 1644991273        
        pv: HILDAQ:elapsedTime
        input:
          timestamp: EVENT:board_0:ch_0:ch_timestamp

    BaselineDynamic_CH<channels>:
        algorithm: BaselineDynamic
        samples: 40
        threshold: 20
        input:
            waveform: EVENT:board_0:ch_<channels>:waveform

    BaselineNaive_CH<channels>:
        algorithm: BaselineNaive
        samples: 40
        input:
            waveform: EVENT:board_0:ch_<channels>:waveform

    CorrectedWaveform_CH<channels>:
        algorithm: CorrectedWaveform
        vpp: 2.5
        adcrange: 16384
        polarity: neg
        units: mV
        input:
            waveform: EVENT:board_0:ch_<channels>:waveform
            baseline: BaselineNaive_CH<channels>

    AverageWaveform_CH<channels>:
        algorithm: AverageWaveform
        input:
            waveform: CorrectedWaveform_CH<channels>

        # -----------------------------------------------------------
        # Window algorithms
        # -----------------------------------------------------------

    TotalWindow:
        algorithm: Window
        window: full

    PulseWindow_CH<channels>:
        algorithm: Window
        left: -50
        right: 0
        input:
            pivot: PulseStart_CH<channels>

    PromptWindow_CH<channels>:
        algorithm: Window
        left: -10
        right: 0
        input:
            pivot: PeakLocation_CH<channels>

    DelayedWindow_CH<channels>:
        algorithm: Window
        left: 0
        right: 20
        pivot index: end
        input:
            pivot: PromptWindow_CH<channels>

        # -----------------------------------------------------------
        # Variables
        # -----------------------------------------------------------

    PeakHeight_CH<channels>:
        algorithm: PeakHeight
        window: true
        input:
            waveform: CorrectedWaveform_CH<channels>
            window: TotalWindow

    PeakLocation_CH<channels>:
        algorithm: PeakLocation
        window: true
        input:
            waveform: CorrectedWaveform_CH<channels>
            window: TotalWindow
    
    ChargeConstant:
        algorithm: ChargeConstant
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
    
    PulseSum_CH<channels>:
        algorithm: Sum
        input:
            waveform: CorrectedWaveform_CH<channels>
            window: PulseWindow_CH<channels>

    PromptCharge_CH<channels>:
        algorithm: Charge
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
        input:
            waveform: CorrectedWaveform_CH<channels>
            window: PromptWindow_CH<channels>

    DelayedCharge_CH<channels>:
        algorithm: Charge
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
        input:
            waveform: CorrectedWaveform_CH<channels>
            window: DelayedWindow_CH<channels>

    TotalCharge_CH<channels>:
        algorithm: Charge
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
        input:
            waveform: CorrectedWaveform_CH<channels>
            window: TotalWindow

    PulseCharge_CH<channels>:
        algorithm: Charge
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
        input:
            waveform: CorrectedWaveform_CH<channels>
            window: PulseWindow_CH<channels>

    PulseStart_CH<channels>:
        algorithm:  CFD
        delay: 5
        scale: 1
        cfd_threshold: 15
        input:
            waveform: CorrectedWaveform_CH<channels>
        output:
            times: PulseCFDTimes_CH<channels>
            trace: PulseCFDTrace_CH<channels>

    TrapezoidWaveform_CH<channels>:
        algorithm: TrapezoidFilter
        rise: 10
        gap: 10
        rate: 500e6
        tau: 2e-6
        zeropole: true
        input:
            waveform: CorrectedWaveform_CH<channels>

    CFD_CH<channels>:
        algorithm: CFD
        delay: 5
        scale: 1
        cfd_threshold: 10
        savecfd: True
        input:
            waveform: TrapezoidWaveform_CH<channels>
        output:
            times: CFDTimes_CH<channels>
            trace: CFDTrace_CH<channels>

    PromptDelayChargeRatio_CH<channels>:
        algorithm: Ratio
        input:
            numerator: PromptCharge_CH<channels>
            denominator: DelayedCharge_CH<channels>

    MeanTime_CH<channels>:
        algorithm: MeanTime
        rate: 500e6
        input:
            waveform: CorrectedWaveform_CH<channels>
            window: PulseWindow_CH<channels>

    PromptDelayChargeRatioCalculator_CH<channels>:
        algorithm: Calculator
        equation: A+(A+B)*(C+D)
        input:
            variables:
                # A: 1
                # B: 11.5
                # C: PromptCharge_CH<channels>
                # D: 3e-1
                - "A = 1; B = 11.5; C = PromptCharge_CH<channels>; D = 3e-1"

    PulseTime_CH<channels>:
        algorithm: TimeConverter
        rate: 500e6
        unit: ns
        input:
            sample_number: PulseStart_CH<channels>

    TimeDifference_CH01:
        algorithm: Difference
        input:
            x1: PulseTime_CH0
            x2: PulseTime_CH1

    Moments_CH<channels>:
        algorithm: Moment
        rate: 500e6
        input:
            waveform: CorrectedWaveform_CH<channels>
            window: TotalWindow
        output:
            mean: Mean_CH<channels>
            stddev: Stddev_CH<channels>
            skew: Skew_CH<channels>
            kurtosis: Kurtosis_CH<channels>

    DAMAX1_CH<channels>:
        algorithm: DAMAX1
        rate: 500e6
        cfd_delay: 10
        input:
            waveform: CorrectedWaveform_CH<channels>
            pulse_start: PulseStart_CH<channels>

    DAMAX2_CH<channels>:
        algorithm: DAMAX2
        rate: 500e6
        cfd_delay: 10
        input:
            waveform: CorrectedWaveform_CH<channels>
            pulse_start: PulseStart_CH<channels>

    FFT_CH<channels>:
        algorithm: FFT
        rate: 500e6
        bins: 100
        input:
            waveform: CorrectedWaveform_CH<channels>
            window: PulseWindow_CH<channels>
        output:
            frequencies: FFT_CH<channels>_Frequencies
            amplitudes: FFT_CH<channels>_Amplitudes

    LeadingEdge_CH<channels>:
        algorithm: LeadingEdgeThreshold
        offset: 5
        threshold: 5
        input:
            waveform: CorrectedWaveform_CH<channels>

        # -----------------------------------------------------------
        # Trees
        # -----------------------------------------------------------
        #
    Channel_<channels>:
        algorithm: TreeMaker
        filltype: event
        input:
            vector<int>: {RawWaveform: EVENT:board_0:ch_<channels>:waveform}
            vector<float>: {CorrectedWaveform: CorrectedWaveform_CH<channels>}
            long: {Timestamp: EVENT:board_0:ch_<channels>:ch_timestamp}
            vector<double>:
                        - FFT_CH<channels>, Moments_CH<channels>
                        - {CFDTrace: CFDTrace_CH<channels>,
                            CFDTimes: CFDTimes_CH<channels>}
                        - {FFT_Amplitudes: FFT_CH<channels>_Amplitudes,
                            FFT_Frequencies: FFT_CH<channels>_Frequencies}
            float:
                -   BaselineDynamic_CH<channels>, BaselineNaive_CH<channels>,
                    PromptDelayChargeRatioCalculator_CH<channels>, CFD_CH<channels>,
                    PulseCharge_CH<channels>, TotalCharge_CH<channels>
                -   {DAMAX1: DAMAX1_CH<channels>, DAMAX2: DAMAX2_CH<channels>}
                -   LeadingEdge_CH<channels>, MeanTime_CH<channels>
                -   {Mean: Mean_CH<channels>,
                        Stddev: Stddev_CH<channels>,
                        Skew: Skew_CH<channels>,
                        Kurtosis: Kurtosis_CH<channels>}
                -   PeakHeight_CH<channels>, PeakLocation_CH<channels>, PulseStart_CH<channels>,
                    PulseTime_CH<channels>, PromptDelayChargeRatio_CH<channels>,
                    PulseSum_CH<channels>

    MultiChannels:
        algorithm: TreeMaker
        filltype: event
        input:
            float: TimeDifference_CH01

    Single_data:
        algorithm: TreeMaker
        filltype: single
        input:
            vector<double>: [AverageWaveform_CH0, AverageWaveform_CH1]
            double: ChargeConstant
