--- 
# -----------------------------------------------------------
# Objects computed by algorithms
# -----------------------------------------------------------

objects:
     # -----------------------------------------------------------
     # Variables
     # -----------------------------------------------------------
     baseMuonCh0:
         algorithm: 
             name: Baseline
         baseline: EVENT:SmallMuon:Channel_0:Baseline

     baseMuonCh1:
         algorithm: 
             name: Baseline
         baseline: EVENT:SmallMuon:Channel_1:Baseline

     waveformMuonCh0:
         algorithm: 
             name: Waveform
             basesub: true
         waveform: EVENT:SmallMuon:Channel_0:RawWaveform

     waveformMuonCh1:
         algorithm: 
             name: Waveform
             basesub: false
         waveform: EVENT:SmallMuon:Channel_1:RawWaveform

     chargeMuonCh0:
         algorithm: 
             name: Charge
         waveform: waveformMuonCh0

     chargeMuonCh1:
         algorithm: 
             name: Charge
         waveform: waveformMuonCh1

     muonTriggeredChannels:
         algorithm: 
             name: Trigger
         triggeredch: EVENT:SmallMuon:EventData:TriggeredChannels
     
     weightMuonCh0:
         algorithm: 
             name: Weight
         value: 1

     weightMuonCh1:
         algorithm: 
             name: Weight
         value: 2


     # -----------------------------------------------------------
     # Plots
     # -----------------------------------------------------------
     stackplot1D:
         algorithm: 
             name: Make1DPlot
             makeratio: True
             regions:
                 muonSelection:
                     channels: 
                         chargeMuonCh0: 100, -10, 9999
                         chargeMuonCh1: 100, -10, 9999
                 muonDetector:
                     event:
                         muonTriggeredChannels: 10, 0, 10
     
     #plot2D:
     #    algorithm: 
     #        name: Make2DPlot
     #        binning:
     #            region1:
     #                var10,var11: nbinsx, xmin, xmax, nbinsy, ymin, ymax
     #                var5,var8: nbinsx, xmin, xmax, nbinsy, ymin, ymax
     #    histograms: filledHists
     
     
     # -----------------------------------------------------------
     # Histograms
     # -----------------------------------------------------------
     #filledHists:
     #    algorithm: 
     #        name: FillHists
     #    histograms: readHists
     
     
     # -----------------------------------------------------------
     # Trees
     # -----------------------------------------------------------
     #tree1:
     #    algorithm: 
     #        name: TreeMaker 
     #        attr1: "My attribute"
     #    variables: var1, var2, var9
     
# EOF
