--- 
# -----------------------------------------------------------
# Objects computed by algorithms
# -----------------------------------------------------------

objects:
     # -----------------------------------------------------------
     # Variables
     # -----------------------------------------------------------
     binning: 
         status: initialise
         algorithm: 
             name: Binning
             regions:
                 region1:
                     var1: nbins, xmin, xmax
                     var2: nbins, xmin, xmax
                     var10,var11: nbinsx, xmin, xmax, nbinsy, ymin, ymax
                     var5,var8: nbinsx, xmin, xmax, nbinsy, ymin, ymax
     
     # -----------------------------------------------------------
     # Plots
     # -----------------------------------------------------------
     stackplot1D:
         status: finalise
         algorithm: 
             name: Make1DPlot
             makestack: True
         histograms: readHists, filledHists
     
     
     stackplot2D:
         status: finalise
         algorithm: 
             name: Make2DPlot
             makestack: True
         histograms: readHists, filledHists
     
     
     # -----------------------------------------------------------
     # Histograms
     # -----------------------------------------------------------
     readHists:
         status: initialise
         algorithm: 
             name: ReadHists
         configuration: binning
     
     
     filledHists:
         status: initialise, execute, finalise
         algorithm: 
             name: FillHists
         configuration: binning 
     
     
     # -----------------------------------------------------------
     # Trees
     # -----------------------------------------------------------
     tree1:
         status: initialise, execute, finalise
         algorithm: 
             name: TreeMaker 
             attr1: "My attribute"
         variables: var1, var2, var3, ...
     
# EOF
