--- 
# -----------------------------------------------------------
# Objects computed by algorithms
# -----------------------------------------------------------

objects:
     # -----------------------------------------------------------
     # Variables
     # -----------------------------------------------------------
     basePMT1:
         algorithm: 
             name: Baseline
         waveform: wfPMT1
     
     basePMT2:
         algorithm:
             name: Baseline
         waveform: wfPMT2

     chargePMT1:
         algorithm: 
             name: Charge
             window: 100
         baseline: basePMT1
     
     chargePMT2:
         algorithm:
             name: Charge
             window: 300
         baseline: basePMT2

     # -----------------------------------------------------------
     # Plots
     # -----------------------------------------------------------
     stackplot1D:
         algorithm: 
             name: Make1DPlot
             makeratio: True
             region1:
                 var1: nbins, xmin, xmax
                 var2: nbins, xmin, xmax
             region1_A:
                 var34: nbins, xmin, xmax
                 var9: nbins, xmin, xmax
         histograms: filledHists
     
     
     plot2D:
         algorithm: 
             name: Make2DPlot
             region1:
                 var10,var11: nbinsx, xmin, xmax, nbinsy, ymin, ymax
                 var5,var8: nbinsx, xmin, xmax, nbinsy, ymin, ymax
         histograms: filledHists
     
     
     # -----------------------------------------------------------
     # Histograms
     # -----------------------------------------------------------
     readHists:
         algorithm: 
             name: ReadHists
     
     
     filledHists:
         algorithm: 
             name: FillHists
         histograms: readHists
     
     
     # -----------------------------------------------------------
     # Trees
     # -----------------------------------------------------------
     tree1:
         algorithm: 
             name: TreeMaker 
             attr1: "My attribute"
         variables: var1, var2, var9
     
# EOF
