--- 
# -----------------------------------------------------------
# Objects computed by algorithms
# -----------------------------------------------------------

objects:
     # -----------------------------------------------------------
     # Variables
     # -----------------------------------------------------------
     baseSmallMuonCh0:
         algorithm: 
             name: Baseline
         baseline: EVENT:GROUP:ch0:SmallMuon:Channel_0:Baseline

     baseSmallMuonCh1:
         algorithm: 
             name: Baseline
         baseline: EVENT:GROUP:ch1:SmallMuon:Channel_1:Baseline

     waveformSmallMuonCh0:
         algorithm: 
             name: Waveform
             basesub: true
         waveform: EVENT:GROUP:ch0:SmallMuon:Channel_0:RawWaveform

     waveformSmallMuonCh1:
         algorithm: 
             name: Waveform
             basesub: false
         waveform: EVENT:GROUP:ch1:SmallMuon:Channel_1:RawWaveform

     chargeSmallMuonCh0:
         algorithm: 
             name: Charge
         waveform: waveformSmallMuonCh0

     chargeSmallMuonCh1:
         algorithm: 
             name: Charge
         waveform: waveformSmallMuonCh1

     muonSmallTriggerTime:
         algorithm: 
             name: Trigger
         triggeredch: EVENT:SmallMuon:EventData:TriggerTime
     
     sabreTriggerTime:
         algorithm: 
             name: Trigger
         triggeredch: EVENT:SABRE:EventData:TriggerTime

     weightSmallMuonCh0:
         algorithm: 
             name: Weight
         value: 1

     weightSmallMuonCh1:
         algorithm: 
             name: Weight
         value: 2


     # -----------------------------------------------------------
     # Plots
     # -----------------------------------------------------------
     smallMuonPlot1D:
         algorithm: 
             name: Make1DPlot
             makeratio: True
             regions:
                 muonSmallSelection:
                     channels: 
                         chargeSmallMuonCh0: 1000, 8600000, 9000000
                         chargeSmallMuonCh1: 1000, 8600000, 9000000
    
     sabreDataPlot1D:
         algorithm: 
             name: Make1DPlot
             makeratio: True
             regions:
                 sabreTrigger:
                     channels: 
                         weightSmallMuonCh0: 100, 0, 100
                         weightSmallMuonCh1: 100, 0, 100


     # -----------------------------------------------------------
     # Histograms
     # -----------------------------------------------------------
     #filledHists:
     #    algorithm: 
     #        name: FillHists
     #    histograms: readHists
     
     
     # -----------------------------------------------------------
     # Trees
     # -----------------------------------------------------------
     #tree1:
     #    algorithm: 
     #        name: TreeMaker 
     #        attr1: "My attribute"
     #    variables: var1, var2, var9
     
# EOF
