# -----------------------------------------------------------
# Objects computed by algorithms
# -----------------------------------------------------------

objects:
        # -----------------------------------------------------------
        # Waveform and Baseline algorithms
        # -----------------------------------------------------------

    RawWaveform_CH0:
        algorithm: RawWaveform
        initialise:
            output:
        input:
            waveform_bt: EVENT:board_0:raw_waveform_ch_0  # Channels need to be specified here
            waveform_md: EVENT:board_0:ch_0:waveform
            waveform_wd: EVENT:RawWaveform

    BaselineDynamic_CH0:
        algorithm: BaselineDynamic
        samples: 40
        threshold: 20
        input:
            waveform: RawWaveform_CH0

    BaselineNaive_CH0:
        algorithm: BaselineNaive
        samples: 40
        input:
            waveform: RawWaveform_CH0

    CorrectedWaveform_CH0:
        algorithm: CorrectedWaveform
        vpp: 2.5
        adcrange: 16384
        polarity: neg
        units: mV
        input:
            waveform: RawWaveform_CH0
            baseline: BaselineNaive_CH0
            wc_waveform: EVENT:GROUP:CH0:RawWaveform

    AverageWaveform_CH0:
        algorithm: AverageWaveform
        input:
            waveform: CorrectedWaveform_CH0

        # -----------------------------------------------------------
        # Window algorithms
        # -----------------------------------------------------------

    TotalWindow:
        algorithm: Window
        window: full

    PromptWindow_CH0:
        algorithm: Window
        left: -10
        right: 0
        input:
            pivot: PeakLocation_CH0


    DelayedWindow_CH0:
        algorithm: Window
        left: 0
        right: 20
        pivot index: end
        input:
            pivot: PromptWindow_CH0


        # -----------------------------------------------------------
        # Variables
        # -----------------------------------------------------------

    Timestamp_CH0:
        algorithm: GetTimestamp

    PeakHeight_CH0:
        algorithm: PeakHeight
        window: true
        input:
            waveform: CorrectedWaveform_CH0
            window: TotalWindow


    PeakLocation_CH0:
        algorithm: PeakLocation
        window: true
        input:
            waveform: CorrectedWaveform_CH0
            window: TotalWindow
    
    ChargeConstant:
        algorithm: ChargeConstant
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
    
    PulseSum_CH0:
        algorithm: Sum
        input:
            waveform: CorrectedWaveform_CH0
            window: PulseWindow_CH0

    PromptCharge_CH0:
        algorithm: Charge
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
        input:
            waveform: CorrectedWaveform_CH0
            window: PromptWindow_CH0


    DelayedCharge_CH0:
        algorithm: Charge
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
        input:
            waveform: CorrectedWaveform_CH0
            window: DelayedWindow_CH0


    TotalCharge_CH0:
        algorithm: Charge
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
        input:
            waveform: CorrectedWaveform_CH0
            window: TotalWindow


    PulseCharge_CH0:
        algorithm: Charge
        impedance: 50
        rate: 500e6
        unit: pC
        waveform_unit: mV
        input:
            waveform: CorrectedWaveform_CH0
            window: PulseWindow_CH0


    PulseStart_CH0:
        algorithm:  CFD
        delay: 5
        scale: 1
        cfd_threshold: 1
        input:
            waveform: CorrectedWaveform_CH0

    TrapezoidWaveform_CH0:
        algorithm: TrapezoidFilter
        rise: 10
        gap: 10
        rate: 500e6
        tau: 2e-6
        zeropole: true
        input:
            waveform: CorrectedWaveform_CH0

    CFD_CH0:
        algorithm: CFD
        delay: 5
        scale: 1
        cfd_threshold: 10
        savecfd: True
        input:
            waveform: TrapezoidWaveform_CH0

    PromptDelayChargeRatio_CH0:
        algorithm: Ratio
        input:
            x1: PromptCharge_CH0
            x2: DelayedCharge_CH0


    MeanTime_CH0:
        algorithm: MeanTime
        rate: 500e6
        input:
            waveform: CorrectedWaveform_CH0
            window: PulseWindow_CH0


######### !! Will need a custom config #########
    PromptDelayChargeRatioCalculator_CH0:
        algorithm: Calculator
        equation: A+(A+B)*(C+D)
        variables:
            A: 1
            B: 11.5
            C: PromptCharge_CH0
            D: 3e-1
            input:
                C: PromptCharge_CH0


    PulseTime_CH0:
        algorithm: TimeConverter
        rate: 500e6
        unit: ns
        input:
            time: PulseStart_CH0

    Moments_CH0:
        algorithm: Moment
        rate: 500e6
        input:
            waveform: CorrectedWaveform_CH0
            window: TotalWindow


    DAMAX1_CH0:
        algorithm: DAMAX1
        rate: 500e6
        cfd_delay: 10
        input:
            waveform: CorrectedWaveform_CH0
            pulse_start: PulseStart_CH0

    DAMAX2_CH0:
        algorithm: DAMAX2
        rate: 500e6
        cfd_delay: 10
        input:
            waveform: CorrectedWaveform_CH0
            pulse_start: PulseStart_CH0
        
    FFT_CH0:
        algorithm: FFT
        rate: 500e6
        bins: 100
        input:
            waveform: CorrectedWaveform_CH0
            window: PulseWindow_CH0

    LeadingEdge_CH0:
        algorithm: LeadingEdgeThreshold
        offset: 5
        threshold: 5
        input:
            waveform: CorrectedWaveform_CH0


        # -----------------------------------------------------------
        # Trees
        # -----------------------------------------------------------
        #
    TreeMaker:
        algorithm: TreeMaker
        trees:
        - Channel_0:
                event:
                    vector<int>: RawWaveform_CH0
                    vector<double>: 
                                - FFT_CH0, Moments_CH0
                                - CorrectedWaveform: CorrectedWaveform_CH0
                    float: 
                        -   PeakHeight_CH0, PeakLocation_CH0, PulseCharge_CH0,
                            TotalCharge_CH0, PulseStart_CH0, PulseTime_CH0, PromptDelayChargeRatio_CH0,
                            MeanTime_CH0, PromptDelayChargeRatioCalculator_CH0,
                            LeadingEdge_CH0, BaselineDynamic_CH0, BaselineNaive_CH0
                        - Timestamp: Timestamp_CH0
                        - {DAMAX1: DAMAX1_CH0, DAMAX2_CH0: DAMAX2_CH0}
                single:
                    vector<double>: AverageWaveform_CH0