# -----------------------------------------------------------
# Objects computed by algorithms
# -----------------------------------------------------------

objects:
    # -----------------------------------------------------------
    # Variables
    # -----------------------------------------------------------

    ############################## WAVEFORMS AND BASELINE #################################

  RawWaveform:
    algorithm:
      name: RawWaveform
    initialise:
      output:
    execute:
      input: EVENT:board_0:ch_3:waveform, EVENT:board_0:raw_waveform_ch_3, EVENT:RawWaveform
      output:
    waveform_bt: EVENT:board_0:raw_waveform_ch_3
    waveform_md: EVENT:board_0:ch_3:waveform
    waveform_wd: EVENT:RawWaveform

  Baseline:
    algorithm:
      name: Baseline
      samples: 40
    execute:
      input: RawWaveform
    waveform: RawWaveform

  CorrectedWaveform:
    algorithm:
      name: CorrectedWaveform
      vpp: 2.5
      adcrange: 65536
      polarity: pos
      units: mV
    initialise:
      output:
    execute:
      input: RawWaveform, Baseline
    waveform: RawWaveform
    baseline: Baseline
    wc_waveform: EVENT:GROUP:CH0:RawWaveform

    # AverageWaveform:
    #     algorithm:
    #         name: AverageWaveform
    #     initialise:
    #         output:
    #     execute:
    #         input: CorrectedWaveform
    #     finalise:
    #         output:
    #     waveform: CorrectedWaveform

  TrapezoidFilter:
    algorithm:
      name: TrapezoidFilter
      rise: 10
      gap: 10
      rate: 500e6
      tau: 2e-6
      zeropole: true
    initialise:
      output:
    execute:
      input: CorrectedWaveform
    waveform: CorrectedWaveform

    ############################## WINDOWS #################################

  TotalWindow:
    algorithm:
      name: Window
      window: full
    initialise:
      output:
    execute:
      output:

  PulseWindow:
    algorithm:
      name: Window
      left: 50
      right: 0
    initialise:
      output:
    execute:
      input: PulseStart
    pivot: PulseStart

  PromptWindow:
    algorithm:
      name: Window
      left: 10
      right: 0
    initialise:
      output:
    execute:
      input: PeakLocation
    pivot: PeakLocation

  DelayedWindow:
    algorithm:
      name: Window
      left: 0
      right: 20
      window pivot: right
    initialise:
      output:
    execute:
      input: PromptWindow
    pivot: PromptWindow

    ############################## VARIABLES #################################

  PeakHeight:
    algorithm:
      name: PeakHeight
      window: true
    initialise:
      output:
    execute:
      input: CorrectedWaveform, TotalWindow
    waveform: CorrectedWaveform
    window: TotalWindow

  PeakLocation:
    algorithm:
      name: PeakLocation
      window: true
    initialise:
      output:
    execute:
      input: CorrectedWaveform, TotalWindow
    waveform: CorrectedWaveform
    window: TotalWindow

  ChargeConstant:
    algorithm:
      name: ChargeConstant
      impedance: 50
      rate: 500e6
      unit: pC
      waveform_unit: mV
    initialise:
      output:

  PromptCharge:
    algorithm:
      name: Charge
      impedance: 50
      rate: 3.2e9
      unit: pC
      waveform_unit: mV
    initialise:
      output:
    execute:
      input: CorrectedWaveform, PromptWindow
    waveform: CorrectedWaveform
    window: PromptWindow

  DelayedCharge:
    algorithm:
      name: Charge
      impedance: 50
      rate: 3.2e9
      unit: pC
      waveform_unit: mV
    initialise:
      output:
    execute:
      input: CorrectedWaveform, DelayedWindow
    waveform: CorrectedWaveform
    window: DelayedWindow

  TotalCharge:
    algorithm:
      name: Charge
      impedance: 50
      rate: 3.2e9
      unit: pC
      waveform_unit: mV
    initialise:
      output:
    execute:
      input: CorrectedWaveform, TotalWindow
    waveform: CorrectedWaveform
    window: TotalWindow

  TotalSum:
    algorithm:
      name: Sum
    execute:
      input: CorrectedWaveform, TotalWindow
    waveform: CorrectedWaveform
    window: TotalWindow

  PulseSum:
    algorithm:
      name: Sum
    execute:
      input: CorrectedWaveform, PulseWindow
    waveform: CorrectedWaveform
    window: PulseWindow

  PulseCharge:
    algorithm:
      name: Charge
      impedance: 50
      rate: 3.2e9
      unit: pC
      waveform_unit: mV
    initialise:
      output:
    execute:
      input: CorrectedWaveform, PulseWindow
    waveform: CorrectedWaveform
    window: PulseWindow

  PulseStart:
    algorithm:
      name: CFD
      delay: 5
      scale: 1
      cfd_threshold: 0
    initialise:
      output:
    execute:
      input: CorrectedWaveform
    waveform: CorrectedWaveform


  CFD_Trap:
    algorithm:
      name: CFD
      delay: 5
      scale: 1
      cfd_threshold: 0
      savecfd: true
    initialise:
      output:
    execute:
      input: TrapezoidFilter
    waveform: TrapezoidFilter

  PromptDelayChargeRatio:
    algorithm:
      name: ChargeRatio
    execute:
      input: PromptCharge, DelayCharge
    charge1: PromptCharge
    charge2: DelayedCharge

  MeanTime:
    algorithm:
      name: MeanTime
      rate: 500e6
    initialise:
      input:
    execute:
      input: CorrectedWaveform, PulseWindow
    waveform: CorrectedWaveform
    window: PulseWindow

  PromptDelayChargeRatioCalculator:
    algorithm:
      name: Calculator
    equation: A+(A+B)*(C+D)
    variables:
      A: 1
      B: 11.5
      C: PromptCharge
      D: 3e-1
    initialise:
      input:
    execute:
      input: PromptCharge

  Skew:
    algorithm:
      name: Moment
      order: 3
      rate: 500e6
    initialise:
      output:
    execute:
      input: CorrectedWaveform, TotalWindow
    waveform: CorrectedWaveform
    window: TotalWindow

  Kurtosis:
    algorithm:
      name: Moment
      order: 4
      rate: 500e6
    initialise:
      output:
    execute:
      input: CorrectedWaveform, TotalWindow
    waveform: CorrectedWaveform
    window: TotalWindow

  SD:
    algorithm:
      name: Moment
      order: 2
      rate: 500e6
    initialise:
      output:
    execute:
      input: CorrectedWaveform, TotalWindow
    waveform: CorrectedWaveform
    window: TotalWindow

  Mean:
    algorithm:
      name: Moment
      order: 1
      rate: 500e6
    initialise:
      output:
    execute:
      input: CorrectedWaveform, PulseWindow
    waveform: CorrectedWaveform
    window: PulseWindow


     # -----------------------------------------------------------
     # Histograms
     # -----------------------------------------------------------
     # -----------------------------------------------------------
     # Trees
     # -----------------------------------------------------------
    #
  TreeMaker:
    algorithm:
      name: TreeMaker
    initialise:
      output:
    execute:
      input: RawWaveform, CorrectedWaveform, Baseline, PeakHeight, PeakLocation, PulseCharge,
        TotalCharge, PulseStart, PromptDelayChargeRatio, PromptCharge, DelayedCharge,
        MeanTime, PromptDelayChargeRatioCalculator, TotalSum, PulseSum, ChargeConstant,
        TrapezoidFilter, CFD_Trap, Skew, Kurtosis, SD, Mean
    finalise:
      output:
    trees:
    - Channel_0:
        event:
          vector:
            int: RawWaveform
            double: CorrectedWaveform, TrapezoidFilter
          scalar:
            float: Baseline, PeakHeight, PeakLocation, PulseCharge, TotalCharge, PulseStart,
              PromptDelayChargeRatio, MeanTime, PromptDelayChargeRatioCalculator,
              TotalSum, PulseSum, CFD_Trap, Skew, Kurtosis, SD, Mean
        single:
                #    vector:
                #        double: AverageWaveform
          scalar:
            double: ChargeConstant
