---
objects:
    Baseline_CH0:
        algorithm:
            name: Baseline
            samples: 40
        execute:
            input: RawWaveform_CH0
        waveform: RawWaveform_CH0
    Baseline_CH1:
        algorithm:
            name: Baseline
            samples: 40
        execute:
            input: RawWaveform_CH1
        waveform: RawWaveform_CH1
    CorrectedWaveform_CH0:
        algorithm:
            adcrange: 16384
            name: CorrectedWaveform
            polarity: neg
            units: mV
            vpp: 2.5
        baseline: Baseline_CH0
        execute:
            input: RawWaveform_CH0, Baseline_CH0
        initialise:
            output: null
        waveform: RawWaveform_CH0
        wc_waveform: EVENT:GROUP:CH0:RawWaveform
    CorrectedWaveform_CH1:
        algorithm:
            adcrange: 16384
            name: CorrectedWaveform
            polarity: neg
            units: mV
            vpp: 2.5
        baseline: Baseline_CH1
        execute:
            input: RawWaveform_CH1, Baseline_CH1
        initialise:
            output: null
        waveform: RawWaveform_CH1
        wc_waveform: EVENT:GROUP:CH1:RawWaveform
    DelayedCharge_CH0:
        algorithm:
            impedance: 50
            name: Charge
            rate: 500e6
            unit: pC
            waveform_unit: mV
        execute:
            input: CorrectedWaveform_CH0, DelayedWindow_CH0
        initialise:
            output: null
        waveform: CorrectedWaveform_CH0
        window: DelayedWindow_CH0
    DelayedCharge_CH1:
        algorithm:
            impedance: 50
            name: Charge
            rate: 500e6
            unit: pC
            waveform_unit: mV
        execute:
            input: CorrectedWaveform_CH1, DelayedWindow_CH1
        initialise:
            output: null
        waveform: CorrectedWaveform_CH1
        window: DelayedWindow_CH1
    DelayedWindow_CH0:
        algorithm:
            left: 20
            name: Window
            right: 0
            window pivot: right
        execute:
            input: PromptWindow_CH0
        initialise:
            output: null
        pivot: PromptWindow_CH0
    DelayedWindow_CH1:
        algorithm:
            left: 20
            name: Window
            right: 0
            window pivot: right
        execute:
            input: PromptWindow_CH1
        initialise:
            output: null
        pivot: PromptWindow_CH1
    Kurtosis_CH0:
        algorithm:
            name: Moment
            order: 4
            rate: 500e6
        execute:
            input: CorrectedWaveform_CH0, TotalWindow_CH0
        initialise:
            output: null
        waveform: CorrectedWaveform_CH0
        window: TotalWindow_CH0
    Kurtosis_CH1:
        algorithm:
            name: Moment
            order: 4
            rate: 500e6
        execute:
            input: CorrectedWaveform_CH1, TotalWindow_CH1
        initialise:
            output: null
        waveform: CorrectedWaveform_CH1
        window: TotalWindow_CH1
    MeanTime_CH0:
        algorithm:
            name: MeanTime
            rate: 500e6
        execute:
            input: CorrectedWaveform_CH0, PulseWindow_CH0
        initialise:
            input: null
        waveform: CorrectedWaveform_CH0
        window: PulseWindow_CH0
    MeanTime_CH1:
        algorithm:
            name: MeanTime
            rate: 500e6
        execute:
            input: CorrectedWaveform_CH1, PulseWindow_CH1
        initialise:
            input: null
        waveform: CorrectedWaveform_CH1
        window: PulseWindow_CH1
    Mean_CH0:
        algorithm:
            name: Moment
            order: 1
            rate: 500e6
        execute:
            input: CorrectedWaveform_CH0, PulseWindow_CH0
        initialise:
            output: null
        waveform: CorrectedWaveform_CH0
        window: PulseWindow_CH0
    Mean_CH1:
        algorithm:
            name: Moment
            order: 1
            rate: 500e6
        execute:
            input: CorrectedWaveform_CH1, PulseWindow_CH1
        initialise:
            output: null
        waveform: CorrectedWaveform_CH1
        window: PulseWindow_CH1
    PeakHeight_CH0:
        algorithm:
            name: PeakHeight
            window: true
        execute:
            input: CorrectedWaveform_CH0, TotalWindow_CH0
        initialise:
            output: null
        waveform: CorrectedWaveform_CH0
        window: TotalWindow_CH0
    PeakHeight_CH1:
        algorithm:
            name: PeakHeight
            window: true
        execute:
            input: CorrectedWaveform_CH1, TotalWindow_CH1
        initialise:
            output: null
        waveform: CorrectedWaveform_CH1
        window: TotalWindow_CH1
    PeakLocation_CH0:
        algorithm:
            name: PeakLocation
            window: true
        execute:
            input: CorrectedWaveform_CH0, TotalWindow_CH0
        initialise:
            output: null
        waveform: CorrectedWaveform_CH0
        window: TotalWindow_CH0
    PeakLocation_CH1:
        algorithm:
            name: PeakLocation
            window: true
        execute:
            input: CorrectedWaveform_CH1, TotalWindow_CH1
        initialise:
            output: null
        waveform: CorrectedWaveform_CH1
        window: TotalWindow_CH1
    PromptCharge_CH0:
        algorithm:
            impedance: 50
            name: Charge
            rate: 500e6
            unit: pC
            waveform_unit: mV
        execute:
            input: CorrectedWaveform_CH0, PromptWindow_CH0
        initialise:
            output: null
        waveform: CorrectedWaveform_CH0
        window: PromptWindow_CH0
    PromptCharge_CH1:
        algorithm:
            impedance: 50
            name: Charge
            rate: 500e6
            unit: pC
            waveform_unit: mV
        execute:
            input: CorrectedWaveform_CH1, PromptWindow_CH1
        initialise:
            output: null
        waveform: CorrectedWaveform_CH1
        window: PromptWindow_CH1
    PromptDelayChargeRatioCalculator_CH0:
        algorithm:
            name: Calculator
        equation: A+(A+B)*(C+D)
        execute:
            input: PromptCharge_CH0
        initialise:
            input: null
        variables:
            A: 1
            B: 11.5
            C: PromptCharge_CH0
            D: 3e-1
    PromptDelayChargeRatioCalculator_CH1:
        algorithm:
            name: Calculator
        equation: A+(A+B)*(C+D)
        execute:
            input: PromptCharge_CH1
        initialise:
            input: null
        variables:
            A: 1
            B: 11.5
            C: PromptCharge_CH1
            D: 3e-1
    PromptDelayChargeRatio_CH0:
        algorithm:
            name: ChargeRatio
        charge1: PromptCharge_CH0
        charge2: DelayedCharge_CH0
        execute:
            input: PromptCharge_CH0, DelayCharge_CH0
    PromptDelayChargeRatio_CH1:
        algorithm:
            name: ChargeRatio
        charge1: PromptCharge_CH1
        charge2: DelayedCharge_CH1
        execute:
            input: PromptCharge_CH1, DelayCharge_CH1
    PromptWindow_CH0:
        algorithm:
            left: 10
            name: Window
            right: 0
        execute:
            input: PeakLocation_CH0
        initialise:
            output: null
        pivot: PeakLocation_CH0
    PromptWindow_CH1:
        algorithm:
            left: 10
            name: Window
            right: 0
        execute:
            input: PeakLocation_CH1
        initialise:
            output: null
        pivot: PeakLocation_CH1
    PulseCharge_CH0:
        algorithm:
            impedance: 50
            name: Charge
            rate: 500e6
            unit: pC
            waveform_unit: mV
        execute:
            input: CorrectedWaveform_CH0, PulseWindow_CH0
        initialise:
            output: null
        waveform: CorrectedWaveform_CH0
        window: PulseWindow_CH0
    PulseCharge_CH1:
        algorithm:
            impedance: 50
            name: Charge
            rate: 500e6
            unit: pC
            waveform_unit: mV
        execute:
            input: CorrectedWaveform_CH1, PulseWindow_CH1
        initialise:
            output: null
        waveform: CorrectedWaveform_CH1
        window: PulseWindow_CH1
    PulseStart_CH0:
        algorithm:
            cfd_threshold: 1
            delay: 5
            name: CFD
            scale: 1
        execute:
            input: CorrectedWaveform_CH0
        initialise:
            output: null
        waveform: CorrectedWaveform_CH0
    PulseStart_CH1:
        algorithm:
            cfd_threshold: 1
            delay: 5
            name: CFD
            scale: 1
        execute:
            input: CorrectedWaveform_CH1
        initialise:
            output: null
        waveform: CorrectedWaveform_CH1
    PulseTime_CH0:
        algorithm:
            name: TimeConverter
            rate: 500e6
            unit: ns
        execute:
            input: PulseStart_CH0
        initialise:
            output: null
        time: PulseStart_CH0
    PulseTime_CH1:
        algorithm:
            name: TimeConverter
            rate: 500e6
            unit: ns
        execute:
            input: PulseStart_CH1
        initialise:
            output: null
        time: PulseStart_CH1
    PulseWindow_CH0:
        algorithm:
            left: 50
            name: Window
            right: 0
        execute:
            input: PulseStart_CH0
        initialise:
            output: null
        pivot: PulseStart_CH0
    PulseWindow_CH1:
        algorithm:
            left: 50
            name: Window
            right: 0
        execute:
            input: PulseStart_CH1
        initialise:
            output: null
        pivot: PulseStart_CH1
    RawWaveform_CH0:
        algorithm:
            name: RawWaveform
        execute:
            input: EVENT:board_0:ch_0:waveform, EVENT:board_0:raw_waveform_ch_0, EVENT:RawWaveform
            output: null
        initialise:
            output: null
        waveform_bt: EVENT:board_0:raw_waveform_ch_0
        waveform_md: EVENT:board_0:ch_0:waveform
        waveform_wd: EVENT:RawWaveform
    RawWaveform_CH1:
        algorithm:
            name: RawWaveform
        execute:
            input: EVENT:board_0:ch_1:waveform, EVENT:board_0:raw_waveform_ch_1, EVENT:RawWaveform
            output: null
        initialise:
            output: null
        waveform_bt: EVENT:board_0:raw_waveform_ch_1
        waveform_md: EVENT:board_0:ch_1:waveform
        waveform_wd: EVENT:RawWaveform
    SD_CH0:
        algorithm:
            name: Moment
            order: 2
            rate: 500e6
        execute:
            input: CorrectedWaveform_CH0, TotalWindow_CH0
        initialise:
            output: null
        waveform: CorrectedWaveform_CH0
        window: TotalWindow_CH0
    SD_CH1:
        algorithm:
            name: Moment
            order: 2
            rate: 500e6
        execute:
            input: CorrectedWaveform_CH1, TotalWindow_CH1
        initialise:
            output: null
        waveform: CorrectedWaveform_CH1
        window: TotalWindow_CH1
    Skew_CH0:
        algorithm:
            name: Moment
            order: 3
            rate: 500e6
        execute:
            input: CorrectedWaveform_CH0, TotalWindow_CH0
        initialise:
            output: null
        waveform: CorrectedWaveform_CH0
        window: TotalWindow_CH0
    Skew_CH1:
        algorithm:
            name: Moment
            order: 3
            rate: 500e6
        execute:
            input: CorrectedWaveform_CH1, TotalWindow_CH1
        initialise:
            output: null
        waveform: CorrectedWaveform_CH1
        window: TotalWindow_CH1
    TimeDifference_CH01:
        algorithm:
            name: TimeDifference
        execute:
            input: PulseTime_CH0, PulseTime_CH1
        time1: PulseTime_CH0
        time2: PulseTime_CH1
    Timestamp_CH0:
        algorithm:
            name: GetTimestamp
        execute:
            output: null
    Timestamp_CH1:
        algorithm:
            name: GetTimestamp
        execute:
            output: null
    TotalCharge_CH0:
        algorithm:
            impedance: 50
            name: Charge
            rate: 500e6
            unit: pC
            waveform_unit: mV
        execute:
            input: CorrectedWaveform_CH0, TotalWindow_CH0
        initialise:
            output: null
        waveform: CorrectedWaveform_CH0
        window: TotalWindow_CH0
    TotalCharge_CH1:
        algorithm:
            impedance: 50
            name: Charge
            rate: 500e6
            unit: pC
            waveform_unit: mV
        execute:
            input: CorrectedWaveform_CH1, TotalWindow_CH1
        initialise:
            output: null
        waveform: CorrectedWaveform_CH1
        window: TotalWindow_CH1
    TotalWindow_CH0:
        algorithm:
            name: Window
            window: full
        execute:
            output: null
        initialise:
            output: null
    TotalWindow_CH1:
        algorithm:
            name: Window
            window: full
        execute:
            output: null
        initialise:
            output: null
    TreeMaker:
        algorithm:
            name: TreeMaker
        execute:
            input: TimeDifference_CH01, RawWaveform_CH0, CorrectedWaveform_CH0, Baseline_CH0,
                PeakHeight_CH0, PeakLocation_CH0, PulseCharge_CH0, TotalCharge_CH0,
                PulseStart_CH0, PulseTime_CH0, PromptDelayChargeRatio_CH0, PromptCharge_CH0,
                DelayedCharge_CH0, MeanTime_CH0, PromptDelayChargeRatioCalculator_CH0,
                Skew_CH0, Kurtosis_CH0, SD_CH0, Mean_CH0, Timestamp_CH0, RawWaveform_CH1,
                CorrectedWaveform_CH1, Baseline_CH1, PeakHeight_CH1, PeakLocation_CH1,
                PulseCharge_CH1, TotalCharge_CH1, PulseStart_CH1, PulseTime_CH1, PromptDelayChargeRatio_CH1,
                PromptCharge_CH1, DelayedCharge_CH1, MeanTime_CH1, PromptDelayChargeRatioCalculator_CH1,
                Skew_CH1, Kurtosis_CH1, SD_CH1, Mean_CH1, Timestamp_CH1
        finalise:
            output: null
        initialise:
            output: null
        trees:
        -   Channel_0:
                event:
                    scalar:
                        float: Baseline_CH0, PeakHeight_CH0, PeakLocation_CH0, PulseCharge_CH0,
                            TotalCharge_CH0, PulseStart_CH0, PulseTime_CH0, PromptDelayChargeRatio_CH0,
                            MeanTime_CH0, PromptDelayChargeRatioCalculator_CH0, Skew_CH0,
                            Kurtosis_CH0, SD_CH0, Mean_CH0, Timestamp_CH0
                    vector:
                        double: CorrectedWaveform_CH0
                        int: RawWaveform_CH0
            Channel_1:
                event:
                    scalar:
                        float: Baseline_CH1, PeakHeight_CH1, PeakLocation_CH1, PulseCharge_CH1,
                            TotalCharge_CH1, PulseStart_CH1, PulseTime_CH1, PromptDelayChargeRatio_CH1,
                            MeanTime_CH1, PromptDelayChargeRatioCalculator_CH1, Skew_CH1,
                            Kurtosis_CH1, SD_CH1, Mean_CH1, Timestamp_CH1
                    vector:
                        double: CorrectedWaveform_CH1
                        int: RawWaveform_CH1
        -   Channel_01:
                event:
                    scalar:
                        float: TimeDifference_CH01
