--- 
input: 
      path:
        - /Users/fscutti/pyrate/myNotebooks/myData/MuonDetData
        - /Users/fscutti/pyrate/myNotebooks/myData/MuonDetOutput
      files:
        - Channel1*
        - Channel2*
      nevents: 
         emin: 0
         emax: -1

config:
      path: /Users/fscutti/pyrate/config
      files: analysis


output:
      path: /Users/fscutti/pyrate/myNotebooks/myOutput
      files:
        output1:
          - region1:plot1:var1
          - region1:plot2
          - region1_A
        output2:
          - "*"


use_nodes: false

# EOF
