--- 

config:
      path: /Users/fscutti/pyrate/config
      files: analysis

input: 
      path:
        - /Users/fscutti/pyrate/myNotebooks/myData/MuonDetData
        - /Users/fscutti/pyrate/myNotebooks/myData/MuonDetOutput
      files:
        - Channel1*
        - Channel2*

output:
      path: /Users/fscutti/pyrate/myNotebooks/myOutput
      files:
        output1:
          - region1:plot1:var1
          - region1:plot2
          - region1_A
        output2:
          - "*"



# ------------------------------------------
# If given, this flag represents the event
# slice size processed by separate Runs. 
# This flag has priority over emin and emax.
# ------------------------------------------
nevents: 1

# ------------------------------------------
# These two flags represent the event number
# considered as a start and stop of the job.
# ------------------------------------------
emin: 0
emax: -1

# ------------------------------------------
# Process separate runs in parallel using a
# cluster system.
# ------------------------------------------
use_nodes: false

# EOF
