--- 

# ------------------------------------------
# These paths are used to look for inputs.
# ------------------------------------------
paths: 
      config: /Users/fscutti/pyrate/config
      input:  /Users/fscutti/pyrate/myNotebooks/myData/MuonDetData
      output: /Users/fscutti/pyrate/myNotebooks/myOutput

# ------------------------------------------
# In the input, strings separated by a comma 
# are interpreted as files gathered in the 
# same block. They are read in parallel 
# event by event.
# ------------------------------------------
files: 
      config: analysis
      input:  ["*"]
      output: test

# ------------------------------------------
# If given, this flag represents the event
# slice size processed by separate Runs. 
# This flag has priority over emin and emax.
# ------------------------------------------
nevents: 1

# ------------------------------------------
# These two flags represent the event number
# considered as a start and stop of the job.
# ------------------------------------------
emin: 0
emax: -1

# ------------------------------------------
# Process separate runs in parallel using a
# cluster system.
# ------------------------------------------
use_nodes: false

# EOF
