--- 
# -----------------------------------------------------------
# Multiple paths can be specified, eventually including the 
# file name if no ambiguity would arise. Files can be 
# specified using part of their names. Names given in the 
# list refer to files which are read independently.
# If comma-separated items are given, these will be read in 
# the same event. 
# The nevents flag can be any integer number implying the
# loop will run up to that value, or the range can be 
# explicitly specified. If nevents: 0 it is implied that the
# job is not an event loop (e.g. limit calculation).
# -----------------------------------------------------------
inputs: 
     input1:
       samples:  Jan,Feb
       group:    wave0,wave1,wave2
       nevents: 
              emin: 0
              emax: -1
       path:
          - /Users/fscutti/pyrate/myNotebooks/myData/MuonDetData/


     input2:
       samples:  source
       nevents: 
              emin: 0
              emax: -1
       path:
          - /Users/fscutti/pyrate/myNotebooks/myData/MuonDetData/



# -----------------------------------------------------------
# Several configuration files can be specified separated with
# a comma.
# -----------------------------------------------------------
configs:
  analysis:
      path: /Users/fscutti/pyrate/config
  reconstruction:
      path: /Users/fscutti/pyrate/config


# -----------------------------------------------------------
# The possibility is given to specify several output files 
# and their content. The content has to refer to objects
# declared in the configuration file in the region field. 
# The object specification is inclusive of all its 
# non-specified sub-fields.
# -----------------------------------------------------------
outputs:
  output1:
    path: /Users/fscutti/pyrate/myNotebooks/myOutput
    objects:
            - regions:region1:plots:plot1:var1
            - regions:region1:plots
  output2:
    path: /Users/fscutti/pyrate/myNotebooks/myOutput
    objects:
            - regions:region1_A
            - regions:region1:trees:tree1
  output3:
    path: /Users/fscutti/pyrate/myNotebooks/myOutput
    objects:
            - "*"

use_nodes: false

# EOF
