#!/usr/bin/env python3

import os
import argparse
import yaml

from pyrate.core.Job import Job

parser = argparse.ArgumentParser(description="Command line options for pyrate")

# -------------------------------------------------------------------
# A single job is identified by just one job configuration file.
# Several of these can be passed to this script using the -j flag.
# This means that the system will launch several jobs in sequence.
# One job corresponds locally to a single instance of a Run.
# -------------------------------------------------------------------
parser.add_argument(
    "--job_config",
    "-j",
    help="job configuration file/s",
    nargs="+",
    required=True,
)

parser.add_argument(
    "--logging_level",
    "-l",
    help="logging level",
    required=False,
    default="CRITICAL",
)

"""
parser.add_argument(
    "--progress_bar",
    "-b",
    help="display progressbar",
    required=False,
    default=True,
)
"""

args = parser.parse_args()


if __name__ == "__main__":
    for j_file in args.job_config:

        j_name = j_file.split("/")[-1].split(".")[0]

        j_config = yaml.full_load(open(j_file, "r"))

        j_log = args.logging_level

        job = Job(j_name, j_config, j_log)

        job.setup()

        job.launch()

# EOF
